//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod tax_category_bulk;
pub mod tax_template_bulk;
pub mod tax_template_row_bulk;
pub mod withholding_category_bulk;

pub use tax_category_bulk::TaxCategoryBulkService;
pub use tax_template_bulk::TaxTemplateBulkService;
pub use tax_template_row_bulk::TaxTemplateRowBulkService;
pub use withholding_category_bulk::WithholdingCategoryBulkService;

// <<< CUSTOM
// END CUSTOM
