//! Bulk operations for TaxTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTaxTemplateDto;
use crate::application::service::TaxTemplateService;
use crate::domain::entity::TaxTemplate;

/// Bulk operation handler for TaxTemplate entities.
///
/// Wraps `TaxTemplateService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TaxTemplateBulkService = GenericBulkService<TaxTemplate, CreateTaxTemplateDto, TaxTemplateService>;

// <<< CUSTOM
// END CUSTOM
