//! Bulk operations for TaxTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTaxTransactionDto;
use crate::application::service::TaxTransactionService;
use crate::domain::entity::TaxTransaction;

/// Bulk operation handler for TaxTransaction entities.
///
/// Wraps `TaxTransactionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TaxTransactionBulkService = GenericBulkService<TaxTransaction, CreateTaxTransactionDto, TaxTransactionService>;

// <<< CUSTOM
// END CUSTOM
