//! Bulk operations for TaxCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTaxCategoryDto;
use crate::application::service::TaxCategoryService;
use crate::domain::entity::TaxCategory;

/// Bulk operation handler for TaxCategory entities.
///
/// Wraps `TaxCategoryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TaxCategoryBulkService = GenericBulkService<TaxCategory, CreateTaxCategoryDto, TaxCategoryService>;

// <<< CUSTOM
// END CUSTOM
