//! Bulk operations for TaxFilingPeriod entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTaxFilingPeriodDto;
use crate::application::service::TaxFilingPeriodService;
use crate::domain::entity::TaxFilingPeriod;

/// Bulk operation handler for TaxFilingPeriod entities.
///
/// Wraps `TaxFilingPeriodService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TaxFilingPeriodBulkService = GenericBulkService<TaxFilingPeriod, CreateTaxFilingPeriodDto, TaxFilingPeriodService>;

// <<< CUSTOM
// END CUSTOM
