//! Bulk operations for WithholdingCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateWithholdingCategoryDto;
use crate::application::service::WithholdingCategoryService;
use crate::domain::entity::WithholdingCategory;

/// Bulk operation handler for WithholdingCategory entities.
///
/// Wraps `WithholdingCategoryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type WithholdingCategoryBulkService = GenericBulkService<WithholdingCategory, CreateWithholdingCategoryDto, WithholdingCategoryService>;

// <<< CUSTOM
// END CUSTOM
