//! CompanyTaxSettings DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CompanyTaxSettings;
use crate::domain::entity::TaxExigibility;
use crate::domain::entity::TaxRoundingMethod;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CompanyTaxSettings
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCompanyTaxSettingsDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "rounding_method")]
    pub rounding_method: TaxRoundingMethod,
    #[serde(alias = "default_exigibility")]
    pub default_exigibility: TaxExigibility,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "cash_basis_transition_account_id"
    )]
    pub cash_basis_transition_account_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CompanyTaxSettings
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCompanyTaxSettingsDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "rounding_method")]
    pub rounding_method: TaxRoundingMethod,
    #[serde(alias = "default_exigibility")]
    pub default_exigibility: TaxExigibility,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "cash_basis_transition_account_id"
    )]
    pub cash_basis_transition_account_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CompanyTaxSettings
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCompanyTaxSettingsDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rounding_method")]
    pub rounding_method: Option<TaxRoundingMethod>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_exigibility")]
    pub default_exigibility: Option<TaxExigibility>,
    #[serde(
        skip_serializing_if = "Option::is_none",
        alias = "cash_basis_transition_account_id"
    )]
    pub cash_basis_transition_account_id: Option<Uuid>,
}

impl PatchCompanyTaxSettingsDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some()
            || self.rounding_method.is_some()
            || self.default_exigibility.is_some()
            || self.cash_basis_transition_account_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CompanyTaxSettings entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyTaxSettingsResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    pub rounding_method: TaxRoundingMethod,
    pub default_exigibility: TaxExigibility,
    pub cash_basis_transition_account_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CompanyTaxSettings entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyTaxSettingsListResponseDto {
    /// List of items
    pub items: Vec<CompanyTaxSettingsResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CompanyTaxSettingsListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<CompanyTaxSettingsResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyTaxSettingsSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub rounding_method: TaxRoundingMethod,
    pub default_exigibility: TaxExigibility,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CompanyTaxSettings> for CompanyTaxSettingsResponseDto {
    fn from(entity: CompanyTaxSettings) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            rounding_method: entity.rounding_method,
            default_exigibility: entity.default_exigibility,
            cash_basis_transition_account_id: entity.cash_basis_transition_account_id,
            metadata: entity.metadata,
        }
    }
}

impl From<CompanyTaxSettings> for CompanyTaxSettingsSummaryDto {
    fn from(entity: CompanyTaxSettings) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            rounding_method: entity.rounding_method,
            default_exigibility: entity.default_exigibility,
            created_at,
        }
    }
}

impl From<CreateCompanyTaxSettingsDto> for CompanyTaxSettings {
    fn from(dto: CreateCompanyTaxSettingsDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            rounding_method: dto.rounding_method,
            default_exigibility: dto.default_exigibility,
            cash_basis_transition_account_id: dto.cash_basis_transition_account_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CompanyTaxSettings> for CompanyTaxSettingsResponseDto {
    fn from(entity: &CompanyTaxSettings) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            rounding_method: entity.rounding_method.clone(),
            default_exigibility: entity.default_exigibility.clone(),
            cash_basis_transition_account_id: entity.cash_basis_transition_account_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCompanyTaxSettingsDto> for CompanyTaxSettings {
    fn from_create_dto(dto: CreateCompanyTaxSettingsDto) -> backbone_core::ServiceResult<Self> {
        Ok(CompanyTaxSettings::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCompanyTaxSettingsDto> for CompanyTaxSettings {
    fn apply_update(
        mut self,
        dto: UpdateCompanyTaxSettingsDto,
    ) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.rounding_method = dto.rounding_method;
        self.default_exigibility = dto.default_exigibility;
        self.cash_basis_transition_account_id = dto.cash_basis_transition_account_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CompanyTaxSettings here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
