//! EFakturDocument DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EFakturDocument;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EFakturStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EFakturDocument
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEFakturDocumentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "tax_transaction_id")]
    pub tax_transaction_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub number: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "transaction_code")]
    pub transaction_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "taxpayer_segment")]
    pub taxpayer_segment: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "assignment_date")]
    pub assignment_date: NaiveDate,
    pub status: EFakturStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "replaces_id")]
    pub replaces_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EFakturDocument
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEFakturDocumentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "tax_transaction_id")]
    pub tax_transaction_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub number: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "transaction_code")]
    pub transaction_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "taxpayer_segment")]
    pub taxpayer_segment: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "assignment_date")]
    pub assignment_date: NaiveDate,
    pub status: EFakturStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "replaces_id")]
    pub replaces_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EFakturDocument
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEFakturDocumentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_transaction_id")]
    pub tax_transaction_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "transaction_code")]
    pub transaction_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "taxpayer_segment")]
    pub taxpayer_segment: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "assignment_date")]
    pub assignment_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<EFakturStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "replaces_id")]
    pub replaces_id: Option<Uuid>,
}

impl PatchEFakturDocumentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.tax_transaction_id.is_some() || self.number.is_some() || self.transaction_code.is_some() || self.taxpayer_segment.is_some() || self.period.is_some() || self.sequence.is_some() || self.assignment_date.is_some() || self.status.is_some() || self.replaces_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EFakturDocument entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EFakturDocumentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub tax_transaction_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub transaction_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub taxpayer_segment: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub assignment_date: NaiveDate,
    pub status: EFakturStatus,
    pub replaces_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EFakturDocument entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EFakturDocumentListResponseDto {
    /// List of items
    pub items: Vec<EFakturDocumentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EFakturDocumentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EFakturDocumentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EFakturDocumentSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub tax_transaction_id: Uuid,
    pub number: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EFakturDocument> for EFakturDocumentResponseDto {
    fn from(entity: EFakturDocument) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            tax_transaction_id: entity.tax_transaction_id,
            number: entity.number,
            transaction_code: entity.transaction_code,
            taxpayer_segment: entity.taxpayer_segment,
            period: entity.period,
            sequence: entity.sequence,
            assignment_date: entity.assignment_date,
            status: entity.status,
            replaces_id: entity.replaces_id,
            metadata: entity.metadata,
        }
    }
}

impl From<EFakturDocument> for EFakturDocumentSummaryDto {
    fn from(entity: EFakturDocument) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            tax_transaction_id: entity.tax_transaction_id,
            number: entity.number,
            created_at,
        }
    }
}

impl From<CreateEFakturDocumentDto> for EFakturDocument {
    fn from(dto: CreateEFakturDocumentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            tax_transaction_id: dto.tax_transaction_id,
            number: dto.number,
            transaction_code: dto.transaction_code,
            taxpayer_segment: dto.taxpayer_segment,
            period: dto.period,
            sequence: dto.sequence,
            assignment_date: dto.assignment_date,
            status: dto.status,
            replaces_id: dto.replaces_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EFakturDocument> for EFakturDocumentResponseDto {
    fn from(entity: &EFakturDocument) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            tax_transaction_id: entity.tax_transaction_id.clone(),
            number: entity.number.clone(),
            transaction_code: entity.transaction_code.clone(),
            taxpayer_segment: entity.taxpayer_segment.clone(),
            period: entity.period.clone(),
            sequence: entity.sequence.clone(),
            assignment_date: entity.assignment_date.clone(),
            status: entity.status.clone(),
            replaces_id: entity.replaces_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEFakturDocumentDto> for EFakturDocument {
    fn from_create_dto(dto: CreateEFakturDocumentDto) -> backbone_core::ServiceResult<Self> {
        Ok(EFakturDocument::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEFakturDocumentDto> for EFakturDocument {
    fn apply_update(mut self, dto: UpdateEFakturDocumentDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.tax_transaction_id = dto.tax_transaction_id;
        self.number = dto.number;
        self.transaction_code = dto.transaction_code;
        self.taxpayer_segment = dto.taxpayer_segment;
        self.period = dto.period;
        self.sequence = dto.sequence;
        self.assignment_date = dto.assignment_date;
        self.status = dto.status;
        self.replaces_id = dto.replaces_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EFakturDocument here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
