//! TaxTag DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TaxTag;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TaxTag
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTaxTagDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TaxTag
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTaxTagDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TaxTag
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTaxTagDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl PatchTaxTagDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TaxTag entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTagResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TaxTag entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTagListResponseDto {
    /// List of items
    pub items: Vec<TaxTagResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TaxTagListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TaxTagResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTagSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TaxTag> for TaxTagResponseDto {
    fn from(entity: TaxTag) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            metadata: entity.metadata,
        }
    }
}

impl From<TaxTag> for TaxTagSummaryDto {
    fn from(entity: TaxTag) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateTaxTagDto> for TaxTag {
    fn from(dto: CreateTaxTagDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            code: dto.code,
            name: dto.name,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TaxTag> for TaxTagResponseDto {
    fn from(entity: &TaxTag) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTaxTagDto> for TaxTag {
    fn from_create_dto(dto: CreateTaxTagDto) -> backbone_core::ServiceResult<Self> {
        Ok(TaxTag::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTaxTagDto> for TaxTag {
    fn apply_update(mut self, dto: UpdateTaxTagDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.code = dto.code;
        self.name = dto.name;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TaxTag here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
