//! TaxRepartitionLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::RepartitionDocumentType;
use crate::domain::entity::RepartitionType;
use crate::domain::entity::TaxRepartitionLine;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TaxRepartitionLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTaxRepartitionLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[serde(alias = "document_type")]
    pub document_type: RepartitionDocumentType,
    #[serde(alias = "repartition_type")]
    pub repartition_type: RepartitionType,
    #[serde(alias = "factor_percent")]
    pub factor_percent: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[serde(alias = "tag_ids")]
    pub tag_ids: Vec<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sort_order")]
    pub sort_order: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TaxRepartitionLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTaxRepartitionLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[serde(alias = "document_type")]
    pub document_type: RepartitionDocumentType,
    #[serde(alias = "repartition_type")]
    pub repartition_type: RepartitionType,
    #[serde(alias = "factor_percent")]
    pub factor_percent: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[serde(alias = "tag_ids")]
    pub tag_ids: Vec<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sort_order")]
    pub sort_order: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TaxRepartitionLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTaxRepartitionLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "document_type")]
    pub document_type: Option<RepartitionDocumentType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "repartition_type")]
    pub repartition_type: Option<RepartitionType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "factor_percent")]
    pub factor_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tag_ids")]
    pub tag_ids: Option<Vec<Uuid>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sort_order")]
    pub sort_order: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PatchTaxRepartitionLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some()
            || self.template_id.is_some()
            || self.document_type.is_some()
            || self.repartition_type.is_some()
            || self.factor_percent.is_some()
            || self.account_id.is_some()
            || self.tag_ids.is_some()
            || self.sort_order.is_some()
            || self.description.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TaxRepartitionLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxRepartitionLineResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub template_id: Uuid,
    pub document_type: RepartitionDocumentType,
    pub repartition_type: RepartitionType,
    pub factor_percent: Decimal,
    pub account_id: Option<Uuid>,
    pub tag_ids: Vec<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sort_order: i32,
    pub description: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TaxRepartitionLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxRepartitionLineListResponseDto {
    /// List of items
    pub items: Vec<TaxRepartitionLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TaxRepartitionLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<TaxRepartitionLineResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxRepartitionLineSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub document_type: RepartitionDocumentType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TaxRepartitionLine> for TaxRepartitionLineResponseDto {
    fn from(entity: TaxRepartitionLine) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            document_type: entity.document_type,
            repartition_type: entity.repartition_type,
            factor_percent: entity.factor_percent,
            account_id: entity.account_id,
            tag_ids: entity.tag_ids,
            sort_order: entity.sort_order,
            description: entity.description,
            metadata: entity.metadata,
        }
    }
}

impl From<TaxRepartitionLine> for TaxRepartitionLineSummaryDto {
    fn from(entity: TaxRepartitionLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            document_type: entity.document_type,
            created_at,
        }
    }
}

impl From<CreateTaxRepartitionLineDto> for TaxRepartitionLine {
    fn from(dto: CreateTaxRepartitionLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            template_id: dto.template_id,
            document_type: dto.document_type,
            repartition_type: dto.repartition_type,
            factor_percent: dto.factor_percent,
            account_id: dto.account_id,
            tag_ids: dto.tag_ids,
            sort_order: dto.sort_order,
            description: dto.description,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TaxRepartitionLine> for TaxRepartitionLineResponseDto {
    fn from(entity: &TaxRepartitionLine) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            template_id: entity.template_id.clone(),
            document_type: entity.document_type.clone(),
            repartition_type: entity.repartition_type.clone(),
            factor_percent: entity.factor_percent.clone(),
            account_id: entity.account_id.clone(),
            tag_ids: entity.tag_ids.clone(),
            sort_order: entity.sort_order.clone(),
            description: entity.description.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTaxRepartitionLineDto> for TaxRepartitionLine {
    fn from_create_dto(dto: CreateTaxRepartitionLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(TaxRepartitionLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTaxRepartitionLineDto> for TaxRepartitionLine {
    fn apply_update(
        mut self,
        dto: UpdateTaxRepartitionLineDto,
    ) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.template_id = dto.template_id;
        self.document_type = dto.document_type;
        self.repartition_type = dto.repartition_type;
        self.factor_percent = dto.factor_percent;
        self.account_id = dto.account_id;
        self.tag_ids = dto.tag_ids;
        self.sort_order = dto.sort_order;
        self.description = dto.description;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TaxRepartitionLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
