//! TaxFilingPeriod DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TaxFilingPeriod;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TaxFilingStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TaxFilingPeriod
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTaxFilingPeriodDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "taxpayer_segment")]
    pub taxpayer_segment: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "next_sequence")]
    pub next_sequence: i32,
    #[serde(alias = "output_total")]
    pub output_total: Decimal,
    #[serde(alias = "input_total")]
    pub input_total: Decimal,
    #[serde(alias = "withholding_total")]
    pub withholding_total: Decimal,
    pub status: TaxFilingStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TaxFilingPeriod
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTaxFilingPeriodDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "taxpayer_segment")]
    pub taxpayer_segment: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "next_sequence")]
    pub next_sequence: i32,
    #[serde(alias = "output_total")]
    pub output_total: Decimal,
    #[serde(alias = "input_total")]
    pub input_total: Decimal,
    #[serde(alias = "withholding_total")]
    pub withholding_total: Decimal,
    pub status: TaxFilingStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TaxFilingPeriod
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTaxFilingPeriodDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "taxpayer_segment")]
    pub taxpayer_segment: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "next_sequence")]
    pub next_sequence: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "output_total")]
    pub output_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "input_total")]
    pub input_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "withholding_total")]
    pub withholding_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<TaxFilingStatus>,
}

impl PatchTaxFilingPeriodDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.period.is_some() || self.npwp.is_some() || self.taxpayer_segment.is_some() || self.next_sequence.is_some() || self.output_total.is_some() || self.input_total.is_some() || self.withholding_total.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TaxFilingPeriod entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxFilingPeriodResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period: NaiveDate,
    pub npwp: Option<String>,
    pub taxpayer_segment: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub next_sequence: i32,
    pub output_total: Decimal,
    pub input_total: Decimal,
    pub withholding_total: Decimal,
    pub status: TaxFilingStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TaxFilingPeriod entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxFilingPeriodListResponseDto {
    /// List of items
    pub items: Vec<TaxFilingPeriodResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TaxFilingPeriodListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TaxFilingPeriodResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxFilingPeriodSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub period: NaiveDate,
    pub npwp: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TaxFilingPeriod> for TaxFilingPeriodResponseDto {
    fn from(entity: TaxFilingPeriod) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            period: entity.period,
            npwp: entity.npwp,
            taxpayer_segment: entity.taxpayer_segment,
            next_sequence: entity.next_sequence,
            output_total: entity.output_total,
            input_total: entity.input_total,
            withholding_total: entity.withholding_total,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<TaxFilingPeriod> for TaxFilingPeriodSummaryDto {
    fn from(entity: TaxFilingPeriod) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            period: entity.period,
            npwp: entity.npwp,
            created_at,
        }
    }
}

impl From<CreateTaxFilingPeriodDto> for TaxFilingPeriod {
    fn from(dto: CreateTaxFilingPeriodDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            period: dto.period,
            npwp: dto.npwp,
            taxpayer_segment: dto.taxpayer_segment,
            next_sequence: dto.next_sequence,
            output_total: dto.output_total,
            input_total: dto.input_total,
            withholding_total: dto.withholding_total,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TaxFilingPeriod> for TaxFilingPeriodResponseDto {
    fn from(entity: &TaxFilingPeriod) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            period: entity.period.clone(),
            npwp: entity.npwp.clone(),
            taxpayer_segment: entity.taxpayer_segment.clone(),
            next_sequence: entity.next_sequence.clone(),
            output_total: entity.output_total.clone(),
            input_total: entity.input_total.clone(),
            withholding_total: entity.withholding_total.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTaxFilingPeriodDto> for TaxFilingPeriod {
    fn from_create_dto(dto: CreateTaxFilingPeriodDto) -> backbone_core::ServiceResult<Self> {
        Ok(TaxFilingPeriod::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTaxFilingPeriodDto> for TaxFilingPeriod {
    fn apply_update(mut self, dto: UpdateTaxFilingPeriodDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.period = dto.period;
        self.npwp = dto.npwp;
        self.taxpayer_segment = dto.taxpayer_segment;
        self.next_sequence = dto.next_sequence;
        self.output_total = dto.output_total;
        self.input_total = dto.input_total;
        self.withholding_total = dto.withholding_total;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TaxFilingPeriod here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

