//! TaxTemplate DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TaxTemplate;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TaxStatus;
use crate::domain::entity::TemplateType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TaxTemplate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTaxTemplateDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "template_type")]
    pub template_type: TemplateType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_category_id")]
    pub tax_category_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_inclusive")]
    pub is_inclusive: bool,
    pub status: TaxStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TaxTemplate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTaxTemplateDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "template_type")]
    pub template_type: TemplateType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_category_id")]
    pub tax_category_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_inclusive")]
    pub is_inclusive: bool,
    pub status: TaxStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TaxTemplate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTaxTemplateDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_type")]
    pub template_type: Option<TemplateType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_category_id")]
    pub tax_category_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_inclusive")]
    pub is_inclusive: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<TaxStatus>,
}

impl PatchTaxTemplateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.template_type.is_some() || self.tax_category_id.is_some() || self.is_inclusive.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TaxTemplate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTemplateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub template_type: TemplateType,
    pub tax_category_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_inclusive: bool,
    pub status: TaxStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TaxTemplate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTemplateListResponseDto {
    /// List of items
    pub items: Vec<TaxTemplateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TaxTemplateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TaxTemplateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTemplateSummaryDto {
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub template_type: TemplateType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TaxTemplate> for TaxTemplateResponseDto {
    fn from(entity: TaxTemplate) -> Self {
        Self {
            id: entity.id,
            code: entity.code,
            name: entity.name,
            template_type: entity.template_type,
            tax_category_id: entity.tax_category_id,
            is_inclusive: entity.is_inclusive,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<TaxTemplate> for TaxTemplateSummaryDto {
    fn from(entity: TaxTemplate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            code: entity.code,
            name: entity.name,
            template_type: entity.template_type,
            created_at,
        }
    }
}

impl From<CreateTaxTemplateDto> for TaxTemplate {
    fn from(dto: CreateTaxTemplateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            code: dto.code,
            name: dto.name,
            template_type: dto.template_type,
            tax_category_id: dto.tax_category_id,
            is_inclusive: dto.is_inclusive,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TaxTemplate> for TaxTemplateResponseDto {
    fn from(entity: &TaxTemplate) -> Self {
        Self {
            id: entity.id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            template_type: entity.template_type.clone(),
            tax_category_id: entity.tax_category_id.clone(),
            is_inclusive: entity.is_inclusive.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTaxTemplateDto> for TaxTemplate {
    fn from_create_dto(dto: CreateTaxTemplateDto) -> backbone_core::ServiceResult<Self> {
        Ok(TaxTemplate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTaxTemplateDto> for TaxTemplate {
    fn apply_update(mut self, dto: UpdateTaxTemplateDto) -> backbone_core::ServiceResult<Self> {
        self.code = dto.code;
        self.name = dto.name;
        self.template_type = dto.template_type;
        self.tax_category_id = dto.tax_category_id;
        self.is_inclusive = dto.is_inclusive;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TaxTemplate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
