//! TaxTemplateRow DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TaxTemplateRow;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ChargeType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TaxTemplateRow
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTaxTemplateRowDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[serde(alias = "charge_type")]
    pub charge_type: ChargeType,
    pub rate: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_withholding")]
    pub is_withholding: bool,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_from")]
    pub effective_from: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "effective_to")]
    pub effective_to: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sort_order")]
    pub sort_order: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TaxTemplateRow
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTaxTemplateRowDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[serde(alias = "charge_type")]
    pub charge_type: ChargeType,
    pub rate: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_withholding")]
    pub is_withholding: bool,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_from")]
    pub effective_from: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "effective_to")]
    pub effective_to: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sort_order")]
    pub sort_order: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TaxTemplateRow
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTaxTemplateRowDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "charge_type")]
    pub charge_type: Option<ChargeType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_withholding")]
    pub is_withholding: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_from")]
    pub effective_from: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_to")]
    pub effective_to: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sort_order")]
    pub sort_order: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PatchTaxTemplateRowDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.template_id.is_some() || self.charge_type.is_some() || self.rate.is_some() || self.account_id.is_some() || self.is_withholding.is_some() || self.effective_from.is_some() || self.effective_to.is_some() || self.sort_order.is_some() || self.description.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TaxTemplateRow entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTemplateRowResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub template_id: Uuid,
    pub charge_type: ChargeType,
    pub rate: Decimal,
    pub account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_withholding: bool,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sort_order: i32,
    pub description: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TaxTemplateRow entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTemplateRowListResponseDto {
    /// List of items
    pub items: Vec<TaxTemplateRowResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TaxTemplateRowListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TaxTemplateRowResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaxTemplateRowSummaryDto {
    pub id: Uuid,
    pub template_id: Uuid,
    pub charge_type: ChargeType,
    pub rate: Decimal,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TaxTemplateRow> for TaxTemplateRowResponseDto {
    fn from(entity: TaxTemplateRow) -> Self {
        Self {
            id: entity.id,
            template_id: entity.template_id,
            charge_type: entity.charge_type,
            rate: entity.rate,
            account_id: entity.account_id,
            is_withholding: entity.is_withholding,
            effective_from: entity.effective_from,
            effective_to: entity.effective_to,
            sort_order: entity.sort_order,
            description: entity.description,
            metadata: entity.metadata,
        }
    }
}

impl From<TaxTemplateRow> for TaxTemplateRowSummaryDto {
    fn from(entity: TaxTemplateRow) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            template_id: entity.template_id,
            charge_type: entity.charge_type,
            rate: entity.rate,
            created_at,
        }
    }
}

impl From<CreateTaxTemplateRowDto> for TaxTemplateRow {
    fn from(dto: CreateTaxTemplateRowDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            template_id: dto.template_id,
            charge_type: dto.charge_type,
            rate: dto.rate,
            account_id: dto.account_id,
            is_withholding: dto.is_withholding,
            effective_from: dto.effective_from,
            effective_to: dto.effective_to,
            sort_order: dto.sort_order,
            description: dto.description,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TaxTemplateRow> for TaxTemplateRowResponseDto {
    fn from(entity: &TaxTemplateRow) -> Self {
        Self {
            id: entity.id.clone(),
            template_id: entity.template_id.clone(),
            charge_type: entity.charge_type.clone(),
            rate: entity.rate.clone(),
            account_id: entity.account_id.clone(),
            is_withholding: entity.is_withholding.clone(),
            effective_from: entity.effective_from.clone(),
            effective_to: entity.effective_to.clone(),
            sort_order: entity.sort_order.clone(),
            description: entity.description.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTaxTemplateRowDto> for TaxTemplateRow {
    fn from_create_dto(dto: CreateTaxTemplateRowDto) -> backbone_core::ServiceResult<Self> {
        Ok(TaxTemplateRow::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTaxTemplateRowDto> for TaxTemplateRow {
    fn apply_update(mut self, dto: UpdateTaxTemplateRowDto) -> backbone_core::ServiceResult<Self> {
        self.template_id = dto.template_id;
        self.charge_type = dto.charge_type;
        self.rate = dto.rate;
        self.account_id = dto.account_id;
        self.is_withholding = dto.is_withholding;
        self.effective_from = dto.effective_from;
        self.effective_to = dto.effective_to;
        self.sort_order = dto.sort_order;
        self.description = dto.description;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TaxTemplateRow here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
