//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod tax_category_specification;
pub mod tax_template_specification;
pub mod tax_template_row_specification;
pub mod withholding_category_specification;

// <<< CUSTOM
// END CUSTOM
