//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod tax_category_domain_policy;
pub mod tax_template_domain_policy;
pub mod tax_template_row_domain_policy;
pub mod withholding_category_domain_policy;

pub use tax_category_domain_policy::TaxCategoryDomainPolicy;
pub use tax_template_domain_policy::TaxTemplateDomainPolicy;
pub use tax_template_row_domain_policy::TaxTemplateRowDomainPolicy;
pub use withholding_category_domain_policy::WithholdingCategoryDomainPolicy;

// <<< CUSTOM
// END CUSTOM
