//! Domain policy for TaxTemplateRow aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::TaxTemplateRow;

/// Domain policy for TaxTemplateRow — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<TaxTemplateRow>` in the `// <<< CUSTOM` zone.
pub type TaxTemplateRowDomainPolicy = PermitAllPolicy<TaxTemplateRow>;

// <<< CUSTOM
// END CUSTOM
