//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod company_tax_settings_service;
pub mod tax_category_service;
pub mod tax_transaction_service;
pub mod e_faktur_document_service;
pub mod tax_filing_period_service;
pub mod tax_tag_service;
pub mod tax_repartition_line_service;
pub mod tax_template_service;
pub mod tax_template_row_service;
pub mod withholding_category_service;

// <<< CUSTOM
// END CUSTOM

pub use company_tax_settings_service::CompanyTaxSettingsService;
pub use tax_category_service::TaxCategoryService;
pub use tax_transaction_service::TaxTransactionService;
pub use e_faktur_document_service::EFakturDocumentService;
pub use tax_filing_period_service::TaxFilingPeriodService;
pub use tax_tag_service::TaxTagService;
pub use tax_repartition_line_service::TaxRepartitionLineService;
pub use tax_template_service::TaxTemplateService;
pub use tax_template_row_service::TaxTemplateRowService;
pub use withholding_category_service::WithholdingCategoryService;
// <<< CUSTOM
// END CUSTOM

// This directory's extension (hand-written; ADR-0031).
include!("mod.ext.rs");
