//! Application service for TaxTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `tax_transaction_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::TaxTransaction;
use crate::infrastructure::persistence::TaxTransactionRepository;
use crate::presentation::dto::{CreateTaxTransactionDto, UpdateTaxTransactionDto};

/// Application service for TaxTransaction entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `tax_transaction_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TaxTransactionServiceCustom {
///     inner: Arc<TaxTransactionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TaxTransactionService = GenericCrudService<
    TaxTransaction,
    CreateTaxTransactionDto,
    UpdateTaxTransactionDto,
    TaxTransactionRepository,
>;

// <<< CUSTOM
// END CUSTOM
