//! Application service for TaxCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `tax_category_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTaxCategoryDto, UpdateTaxCategoryDto};
use crate::domain::entity::TaxCategory;
use crate::infrastructure::persistence::TaxCategoryRepository;

/// Application service for TaxCategory entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `tax_category_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TaxCategoryServiceCustom {
///     inner: Arc<TaxCategoryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TaxCategoryService = GenericCrudService<
    TaxCategory,
    CreateTaxCategoryDto,
    UpdateTaxCategoryDto,
    TaxCategoryRepository,
>;

// <<< CUSTOM
// END CUSTOM
