//! Application service for TaxTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `tax_template_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTaxTemplateDto, UpdateTaxTemplateDto};
use crate::domain::entity::TaxTemplate;
use crate::infrastructure::persistence::TaxTemplateRepository;

/// Application service for TaxTemplate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `tax_template_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TaxTemplateServiceCustom {
///     inner: Arc<TaxTemplateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TaxTemplateService = GenericCrudService<
    TaxTemplate,
    CreateTaxTemplateDto,
    UpdateTaxTemplateDto,
    TaxTemplateRepository,
>;

// <<< CUSTOM
// END CUSTOM
