//! Application service for TaxTag entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `tax_tag_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::TaxTag;
use crate::infrastructure::persistence::TaxTagRepository;
use crate::presentation::dto::{CreateTaxTagDto, UpdateTaxTagDto};

/// Application service for TaxTag entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `tax_tag_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TaxTagServiceCustom {
///     inner: Arc<TaxTagService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TaxTagService =
    GenericCrudService<TaxTag, CreateTaxTagDto, UpdateTaxTagDto, TaxTagRepository>;

// <<< CUSTOM
// END CUSTOM
