//! Application service for TaxTemplateRow entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `tax_template_row_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTaxTemplateRowDto, UpdateTaxTemplateRowDto};
use crate::domain::entity::TaxTemplateRow;
use crate::infrastructure::persistence::TaxTemplateRowRepository;

/// Application service for TaxTemplateRow entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `tax_template_row_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TaxTemplateRowServiceCustom {
///     inner: Arc<TaxTemplateRowService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TaxTemplateRowService = GenericCrudService<
    TaxTemplateRow,
    CreateTaxTemplateRowDto,
    UpdateTaxTemplateRowDto,
    TaxTemplateRowRepository,
>;

// <<< CUSTOM
// END CUSTOM
