//! Application service for WithholdingCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `withholding_category_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWithholdingCategoryDto, UpdateWithholdingCategoryDto};
use crate::domain::entity::WithholdingCategory;
use crate::infrastructure::persistence::WithholdingCategoryRepository;

/// Application service for WithholdingCategory entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `withholding_category_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WithholdingCategoryServiceCustom {
///     inner: Arc<WithholdingCategoryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WithholdingCategoryService = GenericCrudService<
    WithholdingCategory,
    CreateWithholdingCategoryDto,
    UpdateWithholdingCategoryDto,
    WithholdingCategoryRepository,
>;

// <<< CUSTOM
// END CUSTOM
