-- EFakturDocument Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the tax.efaktur_documents table.
-- Customize this file to add your initial data.

-- INSERT INTO tax.efaktur_documents (
--     id,
--     company_id,
--     tax_transaction_id,
--     number,
--     transaction_code,
--     taxpayer_segment,
--     period,
--     sequence,
--     assignment_date,
--     status,
--     replaces_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO tax.efaktur_documents (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

