-- TaxRepartitionLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the tax.tax_repartition_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO tax.tax_repartition_lines (
--     id,
--     company_id,
--     template_id,
--     document_type,
--     repartition_type,
--     factor_percent,
--     account_id,
--     tag_ids,
--     sort_order,
--     description,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO tax.tax_repartition_lines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

