-- TaxTransaction Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the tax.tax_transactions table.
-- Customize this file to add your initial data.

-- INSERT INTO tax.tax_transactions (
--     id,
--     company_id,
--     invoice_ref,
--     invoice_kind,
--     posting_date,
--     taxable_base,
--     output_total,
--     input_total,
--     withholding_total,
--     currency,
--     source,
--     efaktur_document_id,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO tax.tax_transactions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

