-- Migration: Create company_tax_settings table
-- Generated by metaphor-schema

-- Create tax_rounding_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tax_rounding_method') THEN
        CREATE TYPE tax_rounding_method AS ENUM ('round_globally', 'round_per_line');
    END IF;
END
$$;

-- Create tax_exigibility enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tax_exigibility') THEN
        CREATE TYPE tax_exigibility AS ENUM ('on_invoice', 'on_payment');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS tax;

CREATE TABLE IF NOT EXISTS tax.company_tax_settings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    rounding_method tax_rounding_method NOT NULL DEFAULT 'round_globally',
    default_exigibility tax_exigibility NOT NULL DEFAULT 'on_invoice',
    cash_basis_transition_account_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_company_tax_settings_company_id ON tax.company_tax_settings (company_id) WHERE (metadata->>'deleted_at') IS NULL;

-- A company defaulting to cash-basis exigibility must name its transition account;
-- the reconcilability of that account is checked by the write path / TG3 trigger.
ALTER TABLE tax.company_tax_settings
    ADD CONSTRAINT ck_company_tax_settings_caba_requires_transition
    CHECK (default_exigibility <> 'on_payment' OR cash_basis_transition_account_id IS NOT NULL);

-- Company fence (ADR-0014 strict): a session sees only rows whose company_id equals
-- the request-scoped company (`set_config('app.company_id', <uuid>, true)`); an unset
-- var sees zero rows (fail-closed). Same predicate and policy names as every other
-- table in this schema.
ALTER TABLE tax.company_tax_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.company_tax_settings FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS company_tax_settings_company_isolation ON tax.company_tax_settings;
CREATE POLICY company_tax_settings_company_isolation ON tax.company_tax_settings
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_company_tax_settings_metadata_gin ON tax.company_tax_settings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_company_tax_settings_metadata_deleted_at ON tax.company_tax_settings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_company_tax_settings_metadata_created_at ON tax.company_tax_settings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_company_tax_settings_metadata_updated_at ON tax.company_tax_settings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION tax.company_tax_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS company_tax_settings_insert_audit ON tax.company_tax_settings;
CREATE TRIGGER company_tax_settings_insert_audit BEFORE INSERT ON tax.company_tax_settings
    FOR EACH ROW EXECUTE FUNCTION tax.company_tax_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS company_tax_settings_update_audit ON tax.company_tax_settings;
CREATE TRIGGER company_tax_settings_update_audit BEFORE UPDATE ON tax.company_tax_settings
    FOR EACH ROW EXECUTE FUNCTION tax.company_tax_settings_audit_timestamp();
