-- Migration: Create tax_templates table
-- Generated by metaphor-schema

-- Create template_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'template_type') THEN
        CREATE TYPE template_type AS ENUM ('sales', 'purchase');
    END IF;
END
$$;

-- Create tax_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tax_status') THEN
        CREATE TYPE tax_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS tax;

CREATE TABLE IF NOT EXISTS tax.tax_templates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    template_type template_type NOT NULL DEFAULT 'sales',
    tax_category_id UUID,
    is_inclusive BOOLEAN NOT NULL DEFAULT FALSE,
    status tax_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tax_templates_code ON tax.tax_templates (code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_tax_templates_template_type_status ON tax.tax_templates (template_type, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_tax_templates_metadata_gin ON tax.tax_templates USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_tax_templates_metadata_deleted_at ON tax.tax_templates ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_tax_templates_metadata_created_at ON tax.tax_templates ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_tax_templates_metadata_updated_at ON tax.tax_templates ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION tax.tax_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tax_templates_insert_audit ON tax.tax_templates;
CREATE TRIGGER tax_templates_insert_audit BEFORE INSERT ON tax.tax_templates
    FOR EACH ROW EXECUTE FUNCTION tax.tax_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tax_templates_update_audit ON tax.tax_templates;
CREATE TRIGGER tax_templates_update_audit BEFORE UPDATE ON tax.tax_templates
    FOR EACH ROW EXECUTE FUNCTION tax.tax_templates_audit_timestamp();
