-- Company RLS fence for tax module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for tax.tax_categories
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE tax.tax_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.tax_categories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tax_categories_company_isolation ON tax.tax_categories;
CREATE POLICY tax_categories_company_isolation ON tax.tax_categories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for tax.tax_transactions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE tax.tax_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.tax_transactions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tax_transactions_company_isolation ON tax.tax_transactions;
CREATE POLICY tax_transactions_company_isolation ON tax.tax_transactions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for tax.efaktur_documents
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE tax.efaktur_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.efaktur_documents FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS efaktur_documents_company_isolation ON tax.efaktur_documents;
CREATE POLICY efaktur_documents_company_isolation ON tax.efaktur_documents
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for tax.tax_filing_periods
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE tax.tax_filing_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.tax_filing_periods FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tax_filing_periods_company_isolation ON tax.tax_filing_periods;
CREATE POLICY tax_filing_periods_company_isolation ON tax.tax_filing_periods
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for tax.tax_templates
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE tax.tax_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.tax_templates FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tax_templates_company_isolation ON tax.tax_templates;
CREATE POLICY tax_templates_company_isolation ON tax.tax_templates
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for tax.tax_template_rows
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE tax.tax_template_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.tax_template_rows FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tax_template_rows_company_isolation ON tax.tax_template_rows;
CREATE POLICY tax_template_rows_company_isolation ON tax.tax_template_rows
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for tax.withholding_categories
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE tax.withholding_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.withholding_categories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS withholding_categories_company_isolation ON tax.withholding_categories;
CREATE POLICY withholding_categories_company_isolation ON tax.withholding_categories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

