-- Audit Triggers Migration for tax module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: TaxCategory (tax.tax_categories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION tax.tax_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tax_categories_insert_audit ON tax.tax_categories;
CREATE TRIGGER tax_categories_insert_audit BEFORE INSERT ON tax.tax_categories
    FOR EACH ROW EXECUTE FUNCTION tax.tax_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tax_categories_update_audit ON tax.tax_categories;
CREATE TRIGGER tax_categories_update_audit BEFORE UPDATE ON tax.tax_categories
    FOR EACH ROW EXECUTE FUNCTION tax.tax_categories_audit_timestamp();

-- ==============================================================================
-- Table: TaxTemplate (tax.tax_templates)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION tax.tax_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tax_templates_insert_audit ON tax.tax_templates;
CREATE TRIGGER tax_templates_insert_audit BEFORE INSERT ON tax.tax_templates
    FOR EACH ROW EXECUTE FUNCTION tax.tax_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tax_templates_update_audit ON tax.tax_templates;
CREATE TRIGGER tax_templates_update_audit BEFORE UPDATE ON tax.tax_templates
    FOR EACH ROW EXECUTE FUNCTION tax.tax_templates_audit_timestamp();

-- ==============================================================================
-- Table: TaxTemplateRow (tax.tax_template_rows)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION tax.tax_template_rows_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tax_template_rows_insert_audit ON tax.tax_template_rows;
CREATE TRIGGER tax_template_rows_insert_audit BEFORE INSERT ON tax.tax_template_rows
    FOR EACH ROW EXECUTE FUNCTION tax.tax_template_rows_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tax_template_rows_update_audit ON tax.tax_template_rows;
CREATE TRIGGER tax_template_rows_update_audit BEFORE UPDATE ON tax.tax_template_rows
    FOR EACH ROW EXECUTE FUNCTION tax.tax_template_rows_audit_timestamp();

-- ==============================================================================
-- Table: WithholdingCategory (tax.withholding_categories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION tax.withholding_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS withholding_categories_insert_audit ON tax.withholding_categories;
CREATE TRIGGER withholding_categories_insert_audit BEFORE INSERT ON tax.withholding_categories
    FOR EACH ROW EXECUTE FUNCTION tax.withholding_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS withholding_categories_update_audit ON tax.withholding_categories;
CREATE TRIGGER withholding_categories_update_audit BEFORE UPDATE ON tax.withholding_categories
    FOR EACH ROW EXECUTE FUNCTION tax.withholding_categories_audit_timestamp();

