-- Migration: Create tax_filing_periods table
-- Generated by metaphor-schema

-- Create tax_filing_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tax_filing_status') THEN
        CREATE TYPE tax_filing_status AS ENUM ('open', 'finalized', 'filed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS tax;

CREATE TABLE IF NOT EXISTS tax.tax_filing_periods (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    period DATE NOT NULL,
    npwp TEXT,
    taxpayer_segment TEXT,
    next_sequence INTEGER NOT NULL DEFAULT 1 CHECK (next_sequence >= 0),
    output_total NUMERIC(18, 2) NOT NULL DEFAULT 0,
    input_total NUMERIC(18, 2) NOT NULL DEFAULT 0,
    withholding_total NUMERIC(18, 2) NOT NULL DEFAULT 0,
    status tax_filing_status NOT NULL DEFAULT 'open',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tax_filing_periods_company_id_period ON tax.tax_filing_periods (company_id, period) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_tax_filing_periods_metadata_gin ON tax.tax_filing_periods USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_tax_filing_periods_metadata_deleted_at ON tax.tax_filing_periods ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_tax_filing_periods_metadata_created_at ON tax.tax_filing_periods ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_tax_filing_periods_metadata_updated_at ON tax.tax_filing_periods ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION tax.tax_filing_periods_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tax_filing_periods_insert_audit ON tax.tax_filing_periods;
CREATE TRIGGER tax_filing_periods_insert_audit BEFORE INSERT ON tax.tax_filing_periods
    FOR EACH ROW EXECUTE FUNCTION tax.tax_filing_periods_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tax_filing_periods_update_audit ON tax.tax_filing_periods;
CREATE TRIGGER tax_filing_periods_update_audit BEFORE UPDATE ON tax.tax_filing_periods
    FOR EACH ROW EXECUTE FUNCTION tax.tax_filing_periods_audit_timestamp();
