-- Migration: Create tax_repartition_lines table
-- Generated by metaphor-schema

-- Enum existence checks are namespace-scoped (pg_type is not): a same-named enum
-- owned by a sibling module in a shared database must not suppress creation here.

-- Create repartition_document_type enum type
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'repartition_document_type' AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.repartition_document_type AS ENUM ('invoice', 'refund');
    END IF;
END
$$;

-- Create repartition_type enum type
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'repartition_type' AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.repartition_type AS ENUM ('base', 'tax');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS tax;

CREATE TABLE IF NOT EXISTS tax.tax_repartition_lines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    template_id UUID NOT NULL,
    document_type repartition_document_type NOT NULL DEFAULT 'invoice',
    repartition_type repartition_type NOT NULL DEFAULT 'tax',
    factor_percent NUMERIC(16, 12) NOT NULL CHECK (factor_percent >= 0),
    account_id UUID,
    tag_ids UUID[] NOT NULL DEFAULT '{}',
    sort_order INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_tax_repartition_lines_template_id_document_type_repartition_type_sort_order ON tax.tax_repartition_lines (template_id, document_type, repartition_type, sort_order);

-- Structural shape of a family line: base lines carry tags only (never an
-- account), and a zero factor is not a routing share.
ALTER TABLE tax.tax_repartition_lines
    ADD CONSTRAINT ck_tax_repartition_lines_base_has_no_account
    CHECK (repartition_type <> 'base' OR account_id IS NULL);
ALTER TABLE tax.tax_repartition_lines
    ADD CONSTRAINT ck_tax_repartition_lines_factor_nonzero
    CHECK (factor_percent <> 0);

-- Company fence (ADR-0014 strict): same predicate and policy names as every
-- other table in this schema; unset var sees zero rows.
ALTER TABLE tax.tax_repartition_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax.tax_repartition_lines FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tax_repartition_lines_company_isolation ON tax.tax_repartition_lines;
CREATE POLICY tax_repartition_lines_company_isolation ON tax.tax_repartition_lines
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_tax_repartition_lines_metadata_gin ON tax.tax_repartition_lines USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_tax_repartition_lines_metadata_deleted_at ON tax.tax_repartition_lines ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_tax_repartition_lines_metadata_created_at ON tax.tax_repartition_lines ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_tax_repartition_lines_metadata_updated_at ON tax.tax_repartition_lines ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION tax.tax_repartition_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tax_repartition_lines_insert_audit ON tax.tax_repartition_lines;
CREATE TRIGGER tax_repartition_lines_insert_audit BEFORE INSERT ON tax.tax_repartition_lines
    FOR EACH ROW EXECUTE FUNCTION tax.tax_repartition_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tax_repartition_lines_update_audit ON tax.tax_repartition_lines;
CREATE TRIGGER tax_repartition_lines_update_audit BEFORE UPDATE ON tax.tax_repartition_lines
    FOR EACH ROW EXECUTE FUNCTION tax.tax_repartition_lines_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE tax.tax_repartition_lines ADD CONSTRAINT fk_tax_repartition_lines_template_id FOREIGN KEY (template_id) REFERENCES tax.tax_templates (id);
