-- Migration: Create efaktur_documents table
-- Generated by metaphor-schema

-- Create e_faktur_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'e_faktur_status') THEN
        CREATE TYPE e_faktur_status AS ENUM ('assigned', 'confirmed', 'voided');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS tax;

CREATE TABLE IF NOT EXISTS tax.efaktur_documents (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    tax_transaction_id UUID NOT NULL,
    number TEXT NOT NULL,
    transaction_code TEXT NOT NULL,
    taxpayer_segment TEXT NOT NULL,
    period DATE NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence >= 0),
    assignment_date DATE NOT NULL,
    status e_faktur_status NOT NULL DEFAULT 'assigned',
    replaces_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_efaktur_documents_company_id_period_sequence ON tax.efaktur_documents (company_id, period, sequence) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_efaktur_documents_company_id_number ON tax.efaktur_documents (company_id, number) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_efaktur_documents_metadata_gin ON tax.efaktur_documents USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_efaktur_documents_metadata_deleted_at ON tax.efaktur_documents ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_efaktur_documents_metadata_created_at ON tax.efaktur_documents ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_efaktur_documents_metadata_updated_at ON tax.efaktur_documents ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION tax.efaktur_documents_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS efaktur_documents_insert_audit ON tax.efaktur_documents;
CREATE TRIGGER efaktur_documents_insert_audit BEFORE INSERT ON tax.efaktur_documents
    FOR EACH ROW EXECUTE FUNCTION tax.efaktur_documents_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS efaktur_documents_update_audit ON tax.efaktur_documents;
CREATE TRIGGER efaktur_documents_update_audit BEFORE UPDATE ON tax.efaktur_documents
    FOR EACH ROW EXECUTE FUNCTION tax.efaktur_documents_audit_timestamp();
