-- Migration: Create tax_template_rows table
-- Generated by metaphor-schema

-- Create charge_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'charge_type') THEN
        CREATE TYPE charge_type AS ENUM ('on_net_total', 'on_previous_row_total', 'actual');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS tax;

CREATE TABLE IF NOT EXISTS tax.tax_template_rows (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    template_id UUID NOT NULL,
    charge_type charge_type NOT NULL DEFAULT 'on_net_total',
    rate NUMERIC NOT NULL,
    account_id UUID,
    is_withholding BOOLEAN NOT NULL DEFAULT FALSE,
    effective_from DATE NOT NULL,
    effective_to DATE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_tax_template_rows_template_id_sort_order ON tax.tax_template_rows (template_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_tax_template_rows_template_id_effective_from ON tax.tax_template_rows (template_id, effective_from);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_tax_template_rows_metadata_gin ON tax.tax_template_rows USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_tax_template_rows_metadata_deleted_at ON tax.tax_template_rows ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_tax_template_rows_metadata_created_at ON tax.tax_template_rows ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_tax_template_rows_metadata_updated_at ON tax.tax_template_rows ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION tax.tax_template_rows_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tax_template_rows_insert_audit ON tax.tax_template_rows;
CREATE TRIGGER tax_template_rows_insert_audit BEFORE INSERT ON tax.tax_template_rows
    FOR EACH ROW EXECUTE FUNCTION tax.tax_template_rows_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tax_template_rows_update_audit ON tax.tax_template_rows;
CREATE TRIGGER tax_template_rows_update_audit BEFORE UPDATE ON tax.tax_template_rows
    FOR EACH ROW EXECUTE FUNCTION tax.tax_template_rows_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE tax.tax_template_rows ADD CONSTRAINT fk_tax_template_rows_template_id FOREIGN KEY (template_id) REFERENCES tax.tax_templates (id);
