//! Domain events for CompanyTaxSettings entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::CompanyTaxSettings;
use backbone_messaging::CrudEvent;

/// Domain events for CompanyTaxSettings — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CompanyTaxSettings>)` variant.
pub type CompanyTaxSettingsEvent = CrudEvent<CompanyTaxSettings>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CompanyTaxSettings events.
pub type CompanyTaxSettingsEventPublisher =
    Arc<dyn CrudEventPublisher<CompanyTaxSettings> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCompanyTaxSettingsEventPublisher = NoOpCrudEventPublisher<CompanyTaxSettings>;
