//! Event handler trait for CompanyTaxSettings events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CompanyTaxSettingsEvent;

/// Event handler for CompanyTaxSettings events.
/// Implement this trait to react to CompanyTaxSettings lifecycle events.
pub trait CompanyTaxSettingsEventHandler: EventHandler<CompanyTaxSettingsEvent> {}
