//! Event handler trait for EFakturDocument events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EFakturDocumentEvent;

/// Event handler for EFakturDocument events.
/// Implement this trait to react to EFakturDocument lifecycle events.
pub trait EFakturDocumentEventHandler: EventHandler<EFakturDocumentEvent> {}
