//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod company_tax_settings_event_handlers;
pub mod company_tax_settings_events;
pub mod e_faktur_document_event_handlers;
pub mod e_faktur_document_events;
pub mod tax_category_event_handlers;
pub mod tax_category_events;
pub mod tax_filing_period_event_handlers;
pub mod tax_filing_period_events;
pub mod tax_repartition_line_event_handlers;
pub mod tax_repartition_line_events;
pub mod tax_tag_event_handlers;
pub mod tax_tag_events;
pub mod tax_template_event_handlers;
pub mod tax_template_events;
pub mod tax_template_row_event_handlers;
pub mod tax_template_row_events;
pub mod tax_transaction_event_handlers;
pub mod tax_transaction_events;
pub mod withholding_category_event_handlers;
pub mod withholding_category_events;

pub use company_tax_settings_event_handlers::CompanyTaxSettingsEventHandler;
pub use company_tax_settings_events::{
    CompanyTaxSettingsEvent, CompanyTaxSettingsEventPublisher, NoopCompanyTaxSettingsEventPublisher,
};
pub use e_faktur_document_event_handlers::EFakturDocumentEventHandler;
pub use e_faktur_document_events::{
    EFakturDocumentEvent, EFakturDocumentEventPublisher, NoopEFakturDocumentEventPublisher,
};
pub use tax_category_event_handlers::TaxCategoryEventHandler;
pub use tax_category_events::{
    NoopTaxCategoryEventPublisher, TaxCategoryEvent, TaxCategoryEventPublisher,
};
pub use tax_filing_period_event_handlers::TaxFilingPeriodEventHandler;
pub use tax_filing_period_events::{
    NoopTaxFilingPeriodEventPublisher, TaxFilingPeriodEvent, TaxFilingPeriodEventPublisher,
};
pub use tax_repartition_line_event_handlers::TaxRepartitionLineEventHandler;
pub use tax_repartition_line_events::{
    NoopTaxRepartitionLineEventPublisher, TaxRepartitionLineEvent, TaxRepartitionLineEventPublisher,
};
pub use tax_tag_event_handlers::TaxTagEventHandler;
pub use tax_tag_events::{NoopTaxTagEventPublisher, TaxTagEvent, TaxTagEventPublisher};
pub use tax_template_event_handlers::TaxTemplateEventHandler;
pub use tax_template_events::{
    NoopTaxTemplateEventPublisher, TaxTemplateEvent, TaxTemplateEventPublisher,
};
pub use tax_template_row_event_handlers::TaxTemplateRowEventHandler;
pub use tax_template_row_events::{
    NoopTaxTemplateRowEventPublisher, TaxTemplateRowEvent, TaxTemplateRowEventPublisher,
};
pub use tax_transaction_event_handlers::TaxTransactionEventHandler;
pub use tax_transaction_events::{
    NoopTaxTransactionEventPublisher, TaxTransactionEvent, TaxTransactionEventPublisher,
};
pub use withholding_category_event_handlers::WithholdingCategoryEventHandler;
pub use withholding_category_events::{
    NoopWithholdingCategoryEventPublisher, WithholdingCategoryEvent,
    WithholdingCategoryEventPublisher,
};

// <<< CUSTOM
// END CUSTOM
