//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod tax_category_events;
pub mod tax_category_event_handlers;
pub mod tax_transaction_events;
pub mod tax_transaction_event_handlers;
pub mod e_faktur_document_events;
pub mod e_faktur_document_event_handlers;
pub mod tax_filing_period_events;
pub mod tax_filing_period_event_handlers;
pub mod tax_template_events;
pub mod tax_template_event_handlers;
pub mod tax_template_row_events;
pub mod tax_template_row_event_handlers;
pub mod withholding_category_events;
pub mod withholding_category_event_handlers;

pub use tax_category_events::{TaxCategoryEvent, TaxCategoryEventPublisher, NoopTaxCategoryEventPublisher};
pub use tax_category_event_handlers::TaxCategoryEventHandler;
pub use tax_transaction_events::{TaxTransactionEvent, TaxTransactionEventPublisher, NoopTaxTransactionEventPublisher};
pub use tax_transaction_event_handlers::TaxTransactionEventHandler;
pub use e_faktur_document_events::{EFakturDocumentEvent, EFakturDocumentEventPublisher, NoopEFakturDocumentEventPublisher};
pub use e_faktur_document_event_handlers::EFakturDocumentEventHandler;
pub use tax_filing_period_events::{TaxFilingPeriodEvent, TaxFilingPeriodEventPublisher, NoopTaxFilingPeriodEventPublisher};
pub use tax_filing_period_event_handlers::TaxFilingPeriodEventHandler;
pub use tax_template_events::{TaxTemplateEvent, TaxTemplateEventPublisher, NoopTaxTemplateEventPublisher};
pub use tax_template_event_handlers::TaxTemplateEventHandler;
pub use tax_template_row_events::{TaxTemplateRowEvent, TaxTemplateRowEventPublisher, NoopTaxTemplateRowEventPublisher};
pub use tax_template_row_event_handlers::TaxTemplateRowEventHandler;
pub use withholding_category_events::{WithholdingCategoryEvent, WithholdingCategoryEventPublisher, NoopWithholdingCategoryEventPublisher};
pub use withholding_category_event_handlers::WithholdingCategoryEventHandler;

// <<< CUSTOM
// END CUSTOM
