//! Event handler trait for TaxTag events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::TaxTagEvent;
use backbone_messaging::EventHandler;

/// Event handler for TaxTag events.
/// Implement this trait to react to TaxTag lifecycle events.
pub trait TaxTagEventHandler: EventHandler<TaxTagEvent> {}
