//! Domain events for TaxTag entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::TaxTag;
use backbone_messaging::CrudEvent;

/// Domain events for TaxTag — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TaxTag>)` variant.
pub type TaxTagEvent = CrudEvent<TaxTag>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TaxTag events.
pub type TaxTagEventPublisher = Arc<dyn CrudEventPublisher<TaxTag> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTaxTagEventPublisher = NoOpCrudEventPublisher<TaxTag>;
