//! Domain events for TaxCategory entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TaxCategory;

/// Domain events for TaxCategory — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TaxCategory>)` variant.
pub type TaxCategoryEvent = CrudEvent<TaxCategory>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TaxCategory events.
pub type TaxCategoryEventPublisher = Arc<dyn CrudEventPublisher<TaxCategory> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTaxCategoryEventPublisher = NoOpCrudEventPublisher<TaxCategory>;
