//! Domain events for TaxTemplateRow entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TaxTemplateRow;

/// Domain events for TaxTemplateRow — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TaxTemplateRow>)` variant.
pub type TaxTemplateRowEvent = CrudEvent<TaxTemplateRow>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TaxTemplateRow events.
pub type TaxTemplateRowEventPublisher = Arc<dyn CrudEventPublisher<TaxTemplateRow> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTaxTemplateRowEventPublisher = NoOpCrudEventPublisher<TaxTemplateRow>;
