//! Event handler trait for TaxFilingPeriod events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TaxFilingPeriodEvent;

/// Event handler for TaxFilingPeriod events.
/// Implement this trait to react to TaxFilingPeriod lifecycle events.
pub trait TaxFilingPeriodEventHandler: EventHandler<TaxFilingPeriodEvent> {}
