//! Domain events for TaxTransaction entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::TaxTransaction;
use backbone_messaging::CrudEvent;

/// Domain events for TaxTransaction — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TaxTransaction>)` variant.
pub type TaxTransactionEvent = CrudEvent<TaxTransaction>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TaxTransaction events.
pub type TaxTransactionEventPublisher = Arc<dyn CrudEventPublisher<TaxTransaction> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTaxTransactionEventPublisher = NoOpCrudEventPublisher<TaxTransaction>;
