//! Event handler trait for TaxTemplateRow events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::TaxTemplateRowEvent;
use backbone_messaging::EventHandler;

/// Event handler for TaxTemplateRow events.
/// Implement this trait to react to TaxTemplateRow lifecycle events.
pub trait TaxTemplateRowEventHandler: EventHandler<TaxTemplateRowEvent> {}
