//! Event handler trait for TaxTransaction events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::TaxTransactionEvent;
use backbone_messaging::EventHandler;

/// Event handler for TaxTransaction events.
/// Implement this trait to react to TaxTransaction lifecycle events.
pub trait TaxTransactionEventHandler: EventHandler<TaxTransactionEvent> {}
