//! Domain events for TaxTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::TaxTemplate;
use backbone_messaging::CrudEvent;

/// Domain events for TaxTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TaxTemplate>)` variant.
pub type TaxTemplateEvent = CrudEvent<TaxTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TaxTemplate events.
pub type TaxTemplateEventPublisher = Arc<dyn CrudEventPublisher<TaxTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTaxTemplateEventPublisher = NoOpCrudEventPublisher<TaxTemplate>;
