//! Event handler trait for TaxRepartitionLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TaxRepartitionLineEvent;

/// Event handler for TaxRepartitionLine events.
/// Implement this trait to react to TaxRepartitionLine lifecycle events.
pub trait TaxRepartitionLineEventHandler: EventHandler<TaxRepartitionLineEvent> {}
