//! Domain events for TaxRepartitionLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::TaxRepartitionLine;
use backbone_messaging::CrudEvent;

/// Domain events for TaxRepartitionLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TaxRepartitionLine>)` variant.
pub type TaxRepartitionLineEvent = CrudEvent<TaxRepartitionLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TaxRepartitionLine events.
pub type TaxRepartitionLineEventPublisher =
    Arc<dyn CrudEventPublisher<TaxRepartitionLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTaxRepartitionLineEventPublisher = NoOpCrudEventPublisher<TaxRepartitionLine>;
