//! Event handler trait for WithholdingCategory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WithholdingCategoryEvent;

/// Event handler for WithholdingCategory events.
/// Implement this trait to react to WithholdingCategory lifecycle events.
pub trait WithholdingCategoryEventHandler: EventHandler<WithholdingCategoryEvent> {}
