//! Domain events for WithholdingCategory entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WithholdingCategory;

/// Domain events for WithholdingCategory — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WithholdingCategory>)` variant.
pub type WithholdingCategoryEvent = CrudEvent<WithholdingCategory>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WithholdingCategory events.
pub type WithholdingCategoryEventPublisher = Arc<dyn CrudEventPublisher<WithholdingCategory> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWithholdingCategoryEventPublisher = NoOpCrudEventPublisher<WithholdingCategory>;
