//! Event handler trait for WithholdingCategory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::WithholdingCategoryEvent;
use backbone_messaging::EventHandler;

/// Event handler for WithholdingCategory events.
/// Implement this trait to react to WithholdingCategory lifecycle events.
pub trait WithholdingCategoryEventHandler: EventHandler<WithholdingCategoryEvent> {}
