//! CompanyTaxSettings seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CompanyTaxSettings data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// COMPANYTAXSETTINGS SEEDER
// ============================================================================

/// Seeder for company_tax_settings
pub struct SeedCompanyTaxSettingsSeeder;

impl SeedCompanyTaxSettingsSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCompanyTaxSettingsSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCompanyTaxSettingsSeeder {
    fn name(&self) -> &'static str {
        "SeedCompanyTaxSettingsSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if tax.company_tax_settings table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM tax.company_tax_settings")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/company_tax_settings_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM tax.company_tax_settings")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
