//! EFakturDocument seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial EFakturDocument data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// EFAKTURDOCUMENT SEEDER
// ============================================================================

/// Seeder for e_faktur_document
pub struct SeedEFakturDocumentSeeder;

impl SeedEFakturDocumentSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEFakturDocumentSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEFakturDocumentSeeder {
    fn name(&self) -> &'static str {
        "SeedEFakturDocumentSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if tax.efaktur_documents table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM tax.efaktur_documents")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/e_faktur_document_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM tax.efaktur_documents")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
