//! TaxTemplate seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TaxTemplate data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TAXTEMPLATE SEEDER
// ============================================================================

/// Seeder for tax_template
pub struct SeedTaxTemplateSeeder;

impl SeedTaxTemplateSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTaxTemplateSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTaxTemplateSeeder {
    fn name(&self) -> &'static str {
        "SeedTaxTemplateSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if tax.tax_templates table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM tax.tax_templates")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/tax_template_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM tax.tax_templates")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

