//! TaxTemplateRow seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TaxTemplateRow data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TAXTEMPLATEROW SEEDER
// ============================================================================

/// Seeder for tax_template_row
pub struct SeedTaxTemplateRowSeeder;

impl SeedTaxTemplateRowSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTaxTemplateRowSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTaxTemplateRowSeeder {
    fn name(&self) -> &'static str {
        "SeedTaxTemplateRowSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if tax.tax_template_rows table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM tax.tax_template_rows")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/tax_template_row_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM tax.tax_template_rows")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

