//! TaxFilingPeriod seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TaxFilingPeriod data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TAXFILINGPERIOD SEEDER
// ============================================================================

/// Seeder for tax_filing_period
pub struct SeedTaxFilingPeriodSeeder;

impl SeedTaxFilingPeriodSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTaxFilingPeriodSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTaxFilingPeriodSeeder {
    fn name(&self) -> &'static str {
        "SeedTaxFilingPeriodSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if tax.tax_filing_periods table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM tax.tax_filing_periods")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/tax_filing_period_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM tax.tax_filing_periods")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
