//! WithholdingCategory seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial WithholdingCategory data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// WITHHOLDINGCATEGORY SEEDER
// ============================================================================

/// Seeder for withholding_category
pub struct SeedWithholdingCategorySeeder;

impl SeedWithholdingCategorySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedWithholdingCategorySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedWithholdingCategorySeeder {
    fn name(&self) -> &'static str {
        "SeedWithholdingCategorySeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if tax.withholding_categories table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM tax.withholding_categories")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/withholding_category_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM tax.withholding_categories")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

