//! Repository trait for EFakturDocument aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EFakturDocument aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{EFakturDocument, EFakturStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EFakturDocumentPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EFakturDocumentPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EFakturDocumentPaginatedResult {
    pub data: Vec<EFakturDocument>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EFakturDocumentFilter {
    pub company_id: Option<Uuid>,
    pub tax_transaction_id: Option<Uuid>,
    pub number: Option<String>,
    pub transaction_code: Option<String>,
    pub taxpayer_segment: Option<String>,
    pub status: Option<EFakturStatus>,
    pub replaces_id: Option<Uuid>,
}

impl EFakturDocumentFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.tax_transaction_id.is_some()
            || self.number.is_some()
            || self.transaction_code.is_some()
            || self.taxpayer_segment.is_some()
            || self.status.is_some()
            || self.replaces_id.is_some()
    }
}

/// Repository trait for EFakturDocument aggregate
///
/// This trait defines the persistence contract for EFakturDocument entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EFakturDocumentRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new e_faktur_document entity
    async fn save(&self, entity: &EFakturDocument) -> Result<EFakturDocument>;

    /// Find e_faktur_document by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EFakturDocument>>;

    /// Find all e_faktur_document entities
    async fn find_all(&self) -> Result<Vec<EFakturDocument>>;

    /// Update e_faktur_document by ID
    async fn update(&self, id: &str, entity: &EFakturDocument) -> Result<Option<EFakturDocument>>;

    /// Delete e_faktur_document by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List e_faktur_document with pagination
    async fn list(
        &self,
        params: EFakturDocumentPaginationParams,
    ) -> Result<EFakturDocumentPaginatedResult>;

    /// List e_faktur_document with pagination and filters
    async fn list_with_filters(
        &self,
        params: EFakturDocumentPaginationParams,
        filters: EFakturDocumentFilter,
    ) -> Result<EFakturDocumentPaginatedResult>;

    /// Count all e_faktur_document entities
    async fn count(&self) -> Result<u64>;

    /// Count e_faktur_document entities matching filters
    async fn count_with_filters(&self, filters: EFakturDocumentFilter) -> Result<u64>;

    /// Check if e_faktur_document exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete e_faktur_document by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted e_faktur_document by ID
    async fn restore(&self, id: &str) -> Result<Option<EFakturDocument>>;

    /// List soft-deleted e_faktur_document entities
    async fn list_deleted(
        &self,
        params: EFakturDocumentPaginationParams,
    ) -> Result<EFakturDocumentPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save e_faktur_document entities
    async fn bulk_save(&self, entities: &[EFakturDocument]) -> Result<Vec<EFakturDocument>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
