//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod tax_category_repository;
pub mod tax_transaction_repository;
pub mod e_faktur_document_repository;
pub mod tax_filing_period_repository;
pub mod tax_template_repository;
pub mod tax_template_row_repository;
pub mod withholding_category_repository;

// Re-exports
pub use tax_category_repository::{
    TaxCategoryRepository,
    TaxCategoryPaginationParams,
    TaxCategoryPaginatedResult,
    TaxCategoryFilter,
};
pub use tax_transaction_repository::{
    TaxTransactionRepository,
    TaxTransactionPaginationParams,
    TaxTransactionPaginatedResult,
    TaxTransactionFilter,
};
pub use e_faktur_document_repository::{
    EFakturDocumentRepository,
    EFakturDocumentPaginationParams,
    EFakturDocumentPaginatedResult,
    EFakturDocumentFilter,
};
pub use tax_filing_period_repository::{
    TaxFilingPeriodRepository,
    TaxFilingPeriodPaginationParams,
    TaxFilingPeriodPaginatedResult,
    TaxFilingPeriodFilter,
};
pub use tax_template_repository::{
    TaxTemplateRepository,
    TaxTemplatePaginationParams,
    TaxTemplatePaginatedResult,
    TaxTemplateFilter,
};
pub use tax_template_row_repository::{
    TaxTemplateRowRepository,
    TaxTemplateRowPaginationParams,
    TaxTemplateRowPaginatedResult,
    TaxTemplateRowFilter,
};
pub use withholding_category_repository::{
    WithholdingCategoryRepository,
    WithholdingCategoryPaginationParams,
    WithholdingCategoryPaginatedResult,
    WithholdingCategoryFilter,
};
