//! Repository trait for TaxRepartitionLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TaxRepartitionLine aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{RepartitionDocumentType, RepartitionType, TaxRepartitionLine};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxRepartitionLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TaxRepartitionLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TaxRepartitionLinePaginatedResult {
    pub data: Vec<TaxRepartitionLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxRepartitionLineFilter {
    pub company_id: Option<Uuid>,
    pub template_id: Option<Uuid>,
    pub document_type: Option<RepartitionDocumentType>,
    pub repartition_type: Option<RepartitionType>,
    pub account_id: Option<Uuid>,
    pub description: Option<String>,
}

impl TaxRepartitionLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.template_id.is_some()
            || self.document_type.is_some()
            || self.repartition_type.is_some()
            || self.account_id.is_some()
            || self.description.is_some()
    }
}

/// Repository trait for TaxRepartitionLine aggregate
///
/// This trait defines the persistence contract for TaxRepartitionLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TaxRepartitionLineRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new tax_repartition_line entity
    async fn save(&self, entity: &TaxRepartitionLine) -> Result<TaxRepartitionLine>;

    /// Find tax_repartition_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TaxRepartitionLine>>;

    /// Find all tax_repartition_line entities
    async fn find_all(&self) -> Result<Vec<TaxRepartitionLine>>;

    /// Update tax_repartition_line by ID
    async fn update(
        &self,
        id: &str,
        entity: &TaxRepartitionLine,
    ) -> Result<Option<TaxRepartitionLine>>;

    /// Delete tax_repartition_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List tax_repartition_line with pagination
    async fn list(
        &self,
        params: TaxRepartitionLinePaginationParams,
    ) -> Result<TaxRepartitionLinePaginatedResult>;

    /// List tax_repartition_line with pagination and filters
    async fn list_with_filters(
        &self,
        params: TaxRepartitionLinePaginationParams,
        filters: TaxRepartitionLineFilter,
    ) -> Result<TaxRepartitionLinePaginatedResult>;

    /// Count all tax_repartition_line entities
    async fn count(&self) -> Result<u64>;

    /// Count tax_repartition_line entities matching filters
    async fn count_with_filters(&self, filters: TaxRepartitionLineFilter) -> Result<u64>;

    /// Check if tax_repartition_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete tax_repartition_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted tax_repartition_line by ID
    async fn restore(&self, id: &str) -> Result<Option<TaxRepartitionLine>>;

    /// List soft-deleted tax_repartition_line entities
    async fn list_deleted(
        &self,
        params: TaxRepartitionLinePaginationParams,
    ) -> Result<TaxRepartitionLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save tax_repartition_line entities
    async fn bulk_save(&self, entities: &[TaxRepartitionLine]) -> Result<Vec<TaxRepartitionLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
