//! Repository trait for TaxTag aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TaxTag aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::TaxTag;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxTagPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TaxTagPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TaxTagPaginatedResult {
    pub data: Vec<TaxTag>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxTagFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
}

impl TaxTagFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some()
    }
}

/// Repository trait for TaxTag aggregate
///
/// This trait defines the persistence contract for TaxTag entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TaxTagRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new tax_tag entity
    async fn save(&self, entity: &TaxTag) -> Result<TaxTag>;

    /// Find tax_tag by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TaxTag>>;

    /// Find all tax_tag entities
    async fn find_all(&self) -> Result<Vec<TaxTag>>;

    /// Update tax_tag by ID
    async fn update(&self, id: &str, entity: &TaxTag) -> Result<Option<TaxTag>>;

    /// Delete tax_tag by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List tax_tag with pagination
    async fn list(&self, params: TaxTagPaginationParams) -> Result<TaxTagPaginatedResult>;

    /// List tax_tag with pagination and filters
    async fn list_with_filters(
        &self,
        params: TaxTagPaginationParams,
        filters: TaxTagFilter,
    ) -> Result<TaxTagPaginatedResult>;

    /// Count all tax_tag entities
    async fn count(&self) -> Result<u64>;

    /// Count tax_tag entities matching filters
    async fn count_with_filters(&self, filters: TaxTagFilter) -> Result<u64>;

    /// Check if tax_tag exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete tax_tag by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted tax_tag by ID
    async fn restore(&self, id: &str) -> Result<Option<TaxTag>>;

    /// List soft-deleted tax_tag entities
    async fn list_deleted(&self, params: TaxTagPaginationParams) -> Result<TaxTagPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save tax_tag entities
    async fn bulk_save(&self, entities: &[TaxTag]) -> Result<Vec<TaxTag>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
