//! Repository trait for TaxCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TaxCategory aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{TaxCategory, TaxKind, TaxStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxCategoryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TaxCategoryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TaxCategoryPaginatedResult {
    pub data: Vec<TaxCategory>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxCategoryFilter {
    pub code: Option<String>,
    pub name: Option<String>,
    pub tax_kind: Option<TaxKind>,
    pub status: Option<TaxStatus>,
}

impl TaxCategoryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.tax_kind.is_some() || self.status.is_some()
    }
}

/// Repository trait for TaxCategory aggregate
///
/// This trait defines the persistence contract for TaxCategory entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TaxCategoryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new tax_category entity
    async fn save(&self, entity: &TaxCategory) -> Result<TaxCategory>;

    /// Find tax_category by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TaxCategory>>;

    /// Find all tax_category entities
    async fn find_all(&self) -> Result<Vec<TaxCategory>>;

    /// Update tax_category by ID
    async fn update(&self, id: &str, entity: &TaxCategory) -> Result<Option<TaxCategory>>;

    /// Delete tax_category by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List tax_category with pagination
    async fn list(&self, params: TaxCategoryPaginationParams) -> Result<TaxCategoryPaginatedResult>;

    /// List tax_category with pagination and filters
    async fn list_with_filters(&self, params: TaxCategoryPaginationParams, filters: TaxCategoryFilter) -> Result<TaxCategoryPaginatedResult>;

    /// Count all tax_category entities
    async fn count(&self) -> Result<u64>;

    /// Count tax_category entities matching filters
    async fn count_with_filters(&self, filters: TaxCategoryFilter) -> Result<u64>;

    /// Check if tax_category exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete tax_category by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted tax_category by ID
    async fn restore(&self, id: &str) -> Result<Option<TaxCategory>>;

    /// List soft-deleted tax_category entities
    async fn list_deleted(&self, params: TaxCategoryPaginationParams) -> Result<TaxCategoryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save tax_category entities
    async fn bulk_save(&self, entities: &[TaxCategory]) -> Result<Vec<TaxCategory>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
