//! Repository trait for TaxTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TaxTransaction aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{TaxTransaction, InvoiceKind, TaxTransactionSource, TaxTransactionStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxTransactionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TaxTransactionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TaxTransactionPaginatedResult {
    pub data: Vec<TaxTransaction>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxTransactionFilter {
    pub company_id: Option<Uuid>,
    pub invoice_ref: Option<Uuid>,
    pub invoice_kind: Option<InvoiceKind>,
    pub currency: Option<String>,
    pub source: Option<TaxTransactionSource>,
    pub efaktur_document_id: Option<Uuid>,
    pub status: Option<TaxTransactionStatus>,
}

impl TaxTransactionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.invoice_ref.is_some() || self.invoice_kind.is_some() || self.currency.is_some() || self.source.is_some() || self.efaktur_document_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for TaxTransaction aggregate
///
/// This trait defines the persistence contract for TaxTransaction entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TaxTransactionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new tax_transaction entity
    async fn save(&self, entity: &TaxTransaction) -> Result<TaxTransaction>;

    /// Find tax_transaction by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TaxTransaction>>;

    /// Find all tax_transaction entities
    async fn find_all(&self) -> Result<Vec<TaxTransaction>>;

    /// Update tax_transaction by ID
    async fn update(&self, id: &str, entity: &TaxTransaction) -> Result<Option<TaxTransaction>>;

    /// Delete tax_transaction by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List tax_transaction with pagination
    async fn list(&self, params: TaxTransactionPaginationParams) -> Result<TaxTransactionPaginatedResult>;

    /// List tax_transaction with pagination and filters
    async fn list_with_filters(&self, params: TaxTransactionPaginationParams, filters: TaxTransactionFilter) -> Result<TaxTransactionPaginatedResult>;

    /// Count all tax_transaction entities
    async fn count(&self) -> Result<u64>;

    /// Count tax_transaction entities matching filters
    async fn count_with_filters(&self, filters: TaxTransactionFilter) -> Result<u64>;

    /// Check if tax_transaction exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete tax_transaction by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted tax_transaction by ID
    async fn restore(&self, id: &str) -> Result<Option<TaxTransaction>>;

    /// List soft-deleted tax_transaction entities
    async fn list_deleted(&self, params: TaxTransactionPaginationParams) -> Result<TaxTransactionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save tax_transaction entities
    async fn bulk_save(&self, entities: &[TaxTransaction]) -> Result<Vec<TaxTransaction>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
