//! Repository trait for TaxFilingPeriod aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TaxFilingPeriod aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{TaxFilingPeriod, TaxFilingStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxFilingPeriodPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TaxFilingPeriodPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TaxFilingPeriodPaginatedResult {
    pub data: Vec<TaxFilingPeriod>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaxFilingPeriodFilter {
    pub company_id: Option<Uuid>,
    pub npwp: Option<String>,
    pub taxpayer_segment: Option<String>,
    pub status: Option<TaxFilingStatus>,
}

impl TaxFilingPeriodFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.npwp.is_some()
            || self.taxpayer_segment.is_some()
            || self.status.is_some()
    }
}

/// Repository trait for TaxFilingPeriod aggregate
///
/// This trait defines the persistence contract for TaxFilingPeriod entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TaxFilingPeriodRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new tax_filing_period entity
    async fn save(&self, entity: &TaxFilingPeriod) -> Result<TaxFilingPeriod>;

    /// Find tax_filing_period by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TaxFilingPeriod>>;

    /// Find all tax_filing_period entities
    async fn find_all(&self) -> Result<Vec<TaxFilingPeriod>>;

    /// Update tax_filing_period by ID
    async fn update(&self, id: &str, entity: &TaxFilingPeriod) -> Result<Option<TaxFilingPeriod>>;

    /// Delete tax_filing_period by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List tax_filing_period with pagination
    async fn list(
        &self,
        params: TaxFilingPeriodPaginationParams,
    ) -> Result<TaxFilingPeriodPaginatedResult>;

    /// List tax_filing_period with pagination and filters
    async fn list_with_filters(
        &self,
        params: TaxFilingPeriodPaginationParams,
        filters: TaxFilingPeriodFilter,
    ) -> Result<TaxFilingPeriodPaginatedResult>;

    /// Count all tax_filing_period entities
    async fn count(&self) -> Result<u64>;

    /// Count tax_filing_period entities matching filters
    async fn count_with_filters(&self, filters: TaxFilingPeriodFilter) -> Result<u64>;

    /// Check if tax_filing_period exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete tax_filing_period by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted tax_filing_period by ID
    async fn restore(&self, id: &str) -> Result<Option<TaxFilingPeriod>>;

    /// List soft-deleted tax_filing_period entities
    async fn list_deleted(
        &self,
        params: TaxFilingPeriodPaginationParams,
    ) -> Result<TaxFilingPeriodPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save tax_filing_period entities
    async fn bulk_save(&self, entities: &[TaxFilingPeriod]) -> Result<Vec<TaxFilingPeriod>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
