//! Repository for CompanyTaxSettings entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the unit tax-posture SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CompanyTaxSettings, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::CompanyTaxSettings;

/// Table name for CompanyTaxSettings entities
pub const TABLE_NAME: &str = "tax.company_tax_settings";

/// A deployment unit's tax posture, as the write service and routes see it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompanyTaxSettingsRecord {
    pub id: Uuid,
    pub rounding_method: String,
    pub default_exigibility: String,
    pub cash_basis_transition_account_id: Option<Uuid>,
}

/// Repository for CompanyTaxSettings entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompanyTaxSettingsRepository(
    backbone_orm::GenericCrudRepository<CompanyTaxSettings, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompanyTaxSettingsRepository {
    type Target = backbone_orm::GenericCrudRepository<CompanyTaxSettings, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl CompanyTaxSettingsRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Unit tax-posture SQL. Lives here (not in the service) per the module's 4-layer rule. Every
/// statement runs on a caller-provided executor — under a decorated host the transaction was
/// bound to the ambient request org scope, so the composing service's row-level fences govern
/// these reads and writes. The one-row-per-unit uniqueness is POSTURE: the composing service's
/// tenancy decorator installs the per-unit partial unique at composition time, and the SELECT
/// below pins the live row deterministically (`ORDER BY id LIMIT 1`) even where multiple rows
/// coexist unfenced.
impl CompanyTaxSettingsRepository {
    /// The unit's live settings row, if any. Absent ⇒ the engine applies the documented defaults
    /// (`round_globally` / `on_invoice`).
    pub async fn find_own(
        &self,
        conn: &mut sqlx::PgConnection,
    ) -> Result<Option<CompanyTaxSettingsRecord>, sqlx::Error> {
        let row: Option<(Uuid, String, String, Option<Uuid>)> = sqlx::query_as(
            r#"SELECT id, rounding_method::text, default_exigibility::text,
                      cash_basis_transition_account_id
               FROM tax.company_tax_settings
               WHERE (metadata->>'deleted_at') IS NULL
               ORDER BY id
               LIMIT 1"#,
        )
        .fetch_optional(conn)
        .await?;
        Ok(row.map(
            |(id, rounding_method, default_exigibility, cash_basis_transition_account_id)| {
                CompanyTaxSettingsRecord {
                    id,
                    rounding_method,
                    default_exigibility,
                    cash_basis_transition_account_id,
                }
            },
        ))
    }

    /// Insert-or-update the unit's single live settings row (PUT semantics): UPDATE the live row
    /// when one exists, otherwise insert. Soft-deleted rows are outside the decorator-installed
    /// per-unit unique, so a re-put after a soft delete simply creates the next live row.
    pub async fn put(
        &self,
        conn: &mut sqlx::PgConnection,
        rounding_method: &str,
        default_exigibility: &str,
        cash_basis_transition_account_id: Option<Uuid>,
    ) -> Result<Uuid, sqlx::Error> {
        let existing: Option<Uuid> = sqlx::query_scalar(
            r#"SELECT id FROM tax.company_tax_settings
               WHERE (metadata->>'deleted_at') IS NULL
               ORDER BY id
               LIMIT 1"#,
        )
        .fetch_optional(&mut *conn)
        .await?;
        match existing {
            Some(id) => {
                sqlx::query(
                    r#"UPDATE tax.company_tax_settings
                       SET rounding_method = $2::tax_rounding_method,
                           default_exigibility = $3::tax_exigibility,
                           cash_basis_transition_account_id = $4,
                           metadata = jsonb_set(COALESCE(metadata, '{}'::jsonb),
                                                '{updated_at}', to_jsonb(NOW()))
                       WHERE id = $1"#,
                )
                .bind(id)
                .bind(rounding_method)
                .bind(default_exigibility)
                .bind(cash_basis_transition_account_id)
                .execute(&mut *conn)
                .await?;
                Ok(id)
            }
            None => {
                let id = Uuid::new_v4();
                sqlx::query(
                    r#"INSERT INTO tax.company_tax_settings
                           (id, rounding_method, default_exigibility,
                            cash_basis_transition_account_id)
                       VALUES ($1, $2::tax_rounding_method, $3::tax_exigibility, $4)"#,
                )
                .bind(id)
                .bind(rounding_method)
                .bind(default_exigibility)
                .bind(cash_basis_transition_account_id)
                .execute(&mut *conn)
                .await?;
                Ok(id)
            }
        }
    }
}

backbone_core::impl_crud_repository!(
    CompanyTaxSettingsRepository,
    CompanyTaxSettings,
    soft_delete
);
