//! Repository for CompanyTaxSettings entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the company tax-posture SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CompanyTaxSettings, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use backbone_orm::company_scope;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::CompanyTaxSettings;

/// Table name for CompanyTaxSettings entities
pub const TABLE_NAME: &str = "tax.company_tax_settings";

/// A company's tax posture, as the write service and routes see it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompanyTaxSettingsRecord {
    pub id: Uuid,
    pub company_id: Uuid,
    pub rounding_method: String,
    pub default_exigibility: String,
    pub cash_basis_transition_account_id: Option<Uuid>,
}

/// Repository for CompanyTaxSettings entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompanyTaxSettingsRepository(
    backbone_orm::GenericCrudRepository<CompanyTaxSettings, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompanyTaxSettingsRepository {
    type Target = backbone_orm::GenericCrudRepository<CompanyTaxSettings, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl CompanyTaxSettingsRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Company tax-posture SQL. Lives here (not in the service) per the module's 4-layer rule.
impl CompanyTaxSettingsRepository {
    /// The company's live settings row, if any. Absent ⇒ the engine applies the
    /// documented defaults (`round_globally` / `on_invoice`). Company-scoped:
    /// runs bound to the ambient request scope so the RLS fence admits it for
    /// non-superuser roles.
    pub async fn find_by_company(
        &self,
        pool: &PgPool,
        company_id: Uuid,
    ) -> Result<Option<CompanyTaxSettingsRecord>, sqlx::Error> {
        let row: Option<(Uuid, Uuid, String, String, Option<Uuid>)> =
            company_scope::fetch_optional_scoped(
                pool,
                sqlx::query_as(
                    r#"SELECT id, company_id, rounding_method::text, default_exigibility::text,
                              cash_basis_transition_account_id
                       FROM tax.company_tax_settings
                       WHERE company_id = $1 AND (metadata->>'deleted_at') IS NULL"#,
                )
                .bind(company_id),
            )
            .await?;
        Ok(row.map(
            |(
                id,
                company_id,
                rounding_method,
                default_exigibility,
                cash_basis_transition_account_id,
            )| {
                CompanyTaxSettingsRecord {
                    id,
                    company_id,
                    rounding_method,
                    default_exigibility,
                    cash_basis_transition_account_id,
                }
            },
        ))
    }

    /// Insert-or-update the company's single live settings row (PUT semantics).
    /// Soft-deleted rows are outside the partial unique index, so a re-put after a
    /// soft delete simply creates the next live row. Company-scoped (RLS fence).
    pub async fn upsert(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        rounding_method: &str,
        default_exigibility: &str,
        cash_basis_transition_account_id: Option<Uuid>,
    ) -> Result<Uuid, sqlx::Error> {
        let id: Uuid = company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"INSERT INTO tax.company_tax_settings
                       (id, company_id, rounding_method, default_exigibility,
                        cash_basis_transition_account_id)
                   VALUES ($1, $2, $3::tax_rounding_method, $4::tax_exigibility, $5)
                   ON CONFLICT (company_id) WHERE (metadata->>'deleted_at') IS NULL
                   DO UPDATE SET rounding_method = EXCLUDED.rounding_method,
                                 default_exigibility = EXCLUDED.default_exigibility,
                                 cash_basis_transition_account_id = EXCLUDED.cash_basis_transition_account_id,
                                 metadata = jsonb_set(tax.company_tax_settings.metadata,
                                                      '{updated_at}', to_jsonb(NOW()))
                   RETURNING id"#,
            )
            .bind(Uuid::new_v4())
            .bind(company_id)
            .bind(rounding_method)
            .bind(default_exigibility)
            .bind(cash_basis_transition_account_id),
        )
        .await?;
        Ok(id)
    }
}

backbone_core::impl_crud_repository!(
    CompanyTaxSettingsRepository,
    CompanyTaxSettings,
    soft_delete
);
