//! Repository for EFakturDocument entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the e-Faktur engine's document-insert SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EFakturDocument, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::EFakturDocument;

/// Table name for EFakturDocument entities
pub const TABLE_NAME: &str = "tax.efaktur_documents";

/// One e-Faktur document row as the listing/export reads see it. `status` is the DB enum text
/// (`assigned` | `confirmed` | `voided`).
#[derive(Debug, Clone)]
pub struct EFakturDocumentRow {
    pub id: Uuid,
    pub tax_transaction_id: Uuid,
    pub number: String,
    pub transaction_code: String,
    pub taxpayer_segment: String,
    pub period: NaiveDate,
    pub sequence: i32,
    pub assignment_date: NaiveDate,
    pub status: String,
}

/// One export row: an e-Faktur document joined to its tax transaction's invoice projection and
/// totals. The DJP CSV consumer (the composing host) joins buyer identity + per-line detail from
/// billing at export time — tax only owns what this row carries.
#[derive(Debug, Clone)]
pub struct EFakturExportRow {
    pub document: EFakturDocumentRow,
    pub invoice_ref: Uuid,
    pub posting_date: NaiveDate,
    pub taxable_base: Decimal,
    pub output_total: Decimal,
}

/// Repository for EFakturDocument entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EFakturDocumentRepository(
    backbone_orm::GenericCrudRepository<EFakturDocument, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EFakturDocumentRepository {
    type Target = backbone_orm::GenericCrudRepository<EFakturDocument, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl EFakturDocumentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a fresh e-Faktur assignment writes. `transaction_code` is fixed at `'010'` (the
/// DJP etax-invoice code) and `status` at `'assigned'::e_faktur_status` — both preserved verbatim
/// from the hand-written original.
pub struct NewEFakturDocumentRow<'a> {
    pub id: Uuid,
    pub tax_transaction_id: Uuid,
    pub number: &'a str,
    pub taxpayer_segment: &'a str,
    pub period: NaiveDate,
    pub sequence: i32,
    pub assignment_date: NaiveDate,
}

/// EFaktur-document SQL. Lives here (not in the service) per the module's 4-layer rule. Every
/// statement runs on a caller-provided connection — under a decorated host the transaction was
/// bound to the ambient request org scope, so the composing service's row-level fences govern
/// these reads and writes; unfenced deployments see the whole table.
impl EFakturDocumentRepository {
    fn document_row(r: &sqlx::postgres::PgRow) -> EFakturDocumentRow {
        EFakturDocumentRow {
            id: r.get("id"),
            tax_transaction_id: r.get("tax_transaction_id"),
            number: r.get("number"),
            transaction_code: r.get("transaction_code"),
            taxpayer_segment: r.get("taxpayer_segment"),
            period: r.get("period"),
            sequence: r.get("sequence"),
            assignment_date: r.get("assignment_date"),
            status: r.get("status"),
        }
    }

    /// Insert the EFakturDocument row that captures a freshly-allocated e-Faktur number. The
    /// `'010'` transaction-code literal and the `'assigned'::e_faktur_status` cast mirror the
    /// original hand-written SQL exactly.
    pub async fn insert(
        &self,
        conn: &mut PgConnection,
        r: &NewEFakturDocumentRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO tax.efaktur_documents
                 (id, tax_transaction_id, number, transaction_code,
                  taxpayer_segment, period, sequence, assignment_date, status)
               VALUES ($1, $2, $3, '010', $4, $5, $6, $7, 'assigned'::e_faktur_status)"#,
        )
        .bind(r.id)
        .bind(r.tax_transaction_id)
        .bind(r.number)
        .bind(r.taxpayer_segment)
        .bind(r.period)
        .bind(r.sequence)
        .bind(r.assignment_date)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Void an assigned e-Faktur (a credit note / cancellation). DJP rule: the sequence number is
    /// PRESERVED — the row stays, only `status` flips to `voided` (the number is never reused, so the
    /// gapless sequence stays intact). Idempotent: re-voiding an already-voided row is a no-op UPDATE.
    pub async fn void_on(
        &self,
        conn: &mut PgConnection,
        efaktur_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            "UPDATE tax.efaktur_documents SET status = 'voided'::e_faktur_status WHERE id = $1",
        )
        .bind(efaktur_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Confirm an assigned e-Faktur (the operator / downstream-system acknowledgement): CAS
    /// `assigned → confirmed`. Returns the number of rows flipped — `0` means the document is not
    /// in `assigned` (the caller reads the row back to distinguish an idempotent re-confirm from a
    /// refusal).
    pub async fn confirm_on(
        &self,
        conn: &mut PgConnection,
        efaktur_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE tax.efaktur_documents
                 SET status = 'confirmed'::e_faktur_status
               WHERE id = $1 AND status = 'assigned'::e_faktur_status"#,
        )
        .bind(efaktur_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Read one document row by id. The id is globally unique; the bound org scope is the fence
    /// defense-in-depth. `Ok(None)` = no such live document.
    pub async fn find_on(
        &self,
        conn: &mut PgConnection,
        efaktur_id: Uuid,
    ) -> Result<Option<EFakturDocumentRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT id, tax_transaction_id, number, transaction_code,
                      taxpayer_segment, period, sequence, assignment_date, status::text AS status
               FROM tax.efaktur_documents
               WHERE id = $1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(efaktur_id)
        .fetch_optional(conn)
        .await?;
        Ok(row.map(|r| Self::document_row(&r)))
    }

    /// The masa pajak's e-Faktur documents, sequence-ascending (the numbering order the DJP CSV
    /// emits). `status` filters by the DB enum text when given. Rides the ambient scope the
    /// caller bound on `conn`.
    pub async fn list_for_period(
        &self,
        conn: &mut PgConnection,
        period: NaiveDate,
        status: Option<&str>,
    ) -> Result<Vec<EFakturDocumentRow>, sqlx::Error> {
        let rows = sqlx::query(
            r#"SELECT id, tax_transaction_id, number, transaction_code,
                      taxpayer_segment, period, sequence, assignment_date, status::text AS status
               FROM tax.efaktur_documents
               WHERE period = $1 AND (metadata->>'deleted_at') IS NULL
                 AND ($2::text IS NULL OR status::text = $2)
               ORDER BY sequence"#,
        )
        .bind(period)
        .bind(status)
        .fetch_all(conn)
        .await?;
        Ok(rows.iter().map(|r| Self::document_row(r)).collect())
    }

    /// The DJP export projection: every live document of the masa pajak joined to its tax
    /// transaction's invoice reference, posting date, and output totals, sequence-ascending. The
    /// composing host joins buyer identity and per-line detail from billing on top of this read —
    /// tax never reads billing directly (zero cargo edges; the events already delivered the
    /// numbers).
    pub async fn list_export_rows(
        &self,
        conn: &mut PgConnection,
        period: NaiveDate,
    ) -> Result<Vec<EFakturExportRow>, sqlx::Error> {
        let rows = sqlx::query(
            r#"SELECT d.id, d.tax_transaction_id, d.number, d.transaction_code,
                      d.taxpayer_segment, d.period, d.sequence, d.assignment_date,
                      d.status::text AS status,
                      t.invoice_ref, t.posting_date, t.taxable_base, t.output_total
               FROM tax.efaktur_documents d
               JOIN tax.tax_transactions t ON t.id = d.tax_transaction_id
               WHERE d.period = $1
                 AND (d.metadata->>'deleted_at') IS NULL
               ORDER BY d.sequence"#,
        )
        .bind(period)
        .fetch_all(conn)
        .await?;
        Ok(rows
            .iter()
            .map(|r| EFakturExportRow {
                document: Self::document_row(r),
                invoice_ref: r.get("invoice_ref"),
                posting_date: r.get("posting_date"),
                taxable_base: r.get("taxable_base"),
                output_total: r.get("output_total"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(EFakturDocumentRepository, EFakturDocument, soft_delete);
