//! Repository for EFakturDocument entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EFakturDocument, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EFakturDocument;

/// Table name for EFakturDocument entities
pub const TABLE_NAME: &str = "tax.efaktur_documents";

/// Repository for EFakturDocument entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EFakturDocumentRepository(
    backbone_orm::GenericCrudRepository<EFakturDocument, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EFakturDocumentRepository {
    type Target = backbone_orm::GenericCrudRepository<EFakturDocument, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EFakturDocumentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EFakturDocumentRepository, EFakturDocument, soft_delete);
