//! Repository for TaxTag entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the tax-tag SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxTag, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use backbone_orm::company_scope;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::TaxTag;

/// Table name for TaxTag entities
pub const TABLE_NAME: &str = "tax.tax_tags";

/// The exact row a validated tax-tag insert writes.
pub struct NewTaxTagRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
}

/// Repository for TaxTag entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxTagRepository(backbone_orm::GenericCrudRepository<TaxTag, backbone_orm::SoftDelete>);

impl std::ops::Deref for TaxTagRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxTag, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl TaxTagRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Tax-tag SQL. Lives here (not in the service) per the module's 4-layer rule.
impl TaxTagRepository {
    /// Existence probe filtered by the caller's company — the friendly
    /// duplicate-code pre-check. Company-scoped (RLS fence).
    pub async fn find_by_code_in_company(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        code: &str,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let found: Option<Uuid> = company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT id FROM tax.tax_tags
                   WHERE company_id = $1 AND code = $2
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(company_id)
            .bind(code),
        )
        .await?;
        Ok(found)
    }

    /// Insert a tax tag. Company-scoped (RLS fence).
    pub async fn insert(&self, pool: &PgPool, r: &NewTaxTagRow<'_>) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO tax.tax_tags (id, company_id, code, name)
                   VALUES ($1, $2, $3, $4)"#,
            )
            .bind(r.id)
            .bind(r.company_id)
            .bind(r.code)
            .bind(r.name),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(TaxTagRepository, TaxTag, soft_delete);
