//! Repository for TaxCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TaxCategory;

/// Table name for TaxCategory entities
pub const TABLE_NAME: &str = "tax.tax_categories";

/// Repository for TaxCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxCategoryRepository(
    backbone_orm::GenericCrudRepository<TaxCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxCategoryRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TaxCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TaxCategoryRepository, TaxCategory, soft_delete);
