//! Repository for TaxTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TaxTemplate;

/// Table name for TaxTemplate entities
pub const TABLE_NAME: &str = "tax.tax_templates";

/// Repository for TaxTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxTemplateRepository(
    backbone_orm::GenericCrudRepository<TaxTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TaxTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TaxTemplateRepository, TaxTemplate, soft_delete);
