//! Repository for TaxFilingPeriod entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxFilingPeriod, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TaxFilingPeriod;

/// Table name for TaxFilingPeriod entities
pub const TABLE_NAME: &str = "tax.tax_filing_periods";

/// Repository for TaxFilingPeriod entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxFilingPeriodRepository(
    backbone_orm::GenericCrudRepository<TaxFilingPeriod, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxFilingPeriodRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxFilingPeriod, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TaxFilingPeriodRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TaxFilingPeriodRepository, TaxFilingPeriod, soft_delete);
