//! Repository for TaxCategory entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated-write path's tax-category SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::TaxCategory;

/// Table name for TaxCategory entities
pub const TABLE_NAME: &str = "tax.tax_categories";

/// Repository for TaxCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxCategoryRepository(
    backbone_orm::GenericCrudRepository<TaxCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxCategoryRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TaxCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated tax-category insert writes.
pub struct NewTaxCategoryRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub tax_kind: &'a str,
}

/// Tax-category SQL. Lives here (not in the service) per the module's 4-layer rule.
impl TaxCategoryRepository {
    /// Existence probe filtered by the caller's company. Defense-in-depth on top of the RLS fence:
    /// a missed request scope returns no rows (fail-closed). `None` here means "no matching row";
    /// the service treats `None` as `CategoryNotFound`.
    pub async fn find_by_id_in_company(
        &self,
        pool: &PgPool,
        id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let found: Option<Uuid> = sqlx::query_scalar(
            r#"SELECT id FROM tax.tax_categories
               WHERE id = $1 AND company_id = $2 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(id)
        .bind(company_id)
        .fetch_optional(pool)
        .await?;
        Ok(found)
    }

    /// Insert a new active tax category. The caller has already established the request scope via
    /// `with_company_scope`; the explicit `company_id` bind is defense-in-depth on top of the RLS
    /// fence. The `$5::tax_kind` cast mirrors the original hand-written SQL exactly.
    pub async fn insert(
        &self,
        pool: &PgPool,
        r: &NewTaxCategoryRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO tax.tax_categories (id, company_id, code, name, tax_kind, status)
               VALUES ($1,$2,$3,$4,$5::tax_kind,'active'::tax_status)"#,
        )
        .bind(r.id).bind(r.company_id).bind(r.code).bind(r.name).bind(r.tax_kind)
        .execute(pool).await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(TaxCategoryRepository, TaxCategory, soft_delete);
