//! Repository for TaxFilingPeriod entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the gapless e-Faktur sequence allocator's SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxFilingPeriod, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use chrono::NaiveDate;
use sqlx::{PgConnection, PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::TaxFilingPeriod;

/// Table name for TaxFilingPeriod entities
pub const TABLE_NAME: &str = "tax.tax_filing_periods";

/// Repository for TaxFilingPeriod entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxFilingPeriodRepository(
    backbone_orm::GenericCrudRepository<TaxFilingPeriod, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxFilingPeriodRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxFilingPeriod, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TaxFilingPeriodRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The gapless allocator's result: the just-allocated sequence number and the taxpayer segment the
/// DJP-format e-Faktur number embeds (`010.<seg>-<mm>.<seq:08>`).
pub struct AllocatedSequence {
    pub seq: i32,
    pub seg: String,
}

/// Tax-filing-period SQL. Lives here (not in the service) per the module's 4-layer rule.
impl TaxFilingPeriodRepository {
    /// Ensure an open `TaxFilingPeriod` row exists for `(company, period)`. Idempotent — if a row
    /// already exists (created by an earlier sales invoice in the same month), the `ON CONFLICT DO
    /// NOTHING` branch skips the insert. The caller has already bound the company on `conn`; the
    /// explicit `company_id` bind is defense-in-depth on top of the RLS fence.
    pub async fn ensure_open(
        &self,
        conn: &mut PgConnection,
        id: Uuid,
        company_id: Uuid,
        period: NaiveDate,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO tax.tax_filing_periods (id, company_id, period, status)
               VALUES ($1, $2, $3, 'open'::tax_filing_status)
               ON CONFLICT (company_id, period) WHERE (metadata->>'deleted_at') IS NULL
               DO NOTHING"#,
        )
        .bind(id).bind(company_id).bind(period)
        .execute(conn).await?;
        Ok(())
    }

    /// Atomically allocate the next gapless sequence number for `(company, period)`.
    ///
    /// The `UPDATE … SET next_sequence = next_sequence + 1 … RETURNING next_sequence - 1` is the
    /// exactly-once allocator: Postgres takes a row-level lock on the matched period row, so
    /// concurrent calls serialize on the per-period sequence — no gaps, no duplicates. The
    /// `RETURNING` value is the *pre-increment* sequence number (`next_sequence - 1` after the
    /// write), which is the number embedded in the DJP-format e-Faktur id. The caller has already
    /// bound the company on `conn`; the `WHERE company_id = $1` filter is defense-in-depth on top
    /// of the RLS fence. The `(metadata->>'deleted_at') IS NULL` predicate preserves the original
    /// skip-soft-deleted behavior verbatim.
    pub async fn allocate_sequence(
        &self,
        conn: &mut PgConnection,
        company_id: Uuid,
        period: NaiveDate,
    ) -> Result<AllocatedSequence, sqlx::Error> {
        let row = sqlx::query(
            r#"UPDATE tax.tax_filing_periods
                 SET next_sequence = next_sequence + 1
               WHERE company_id = $1 AND period = $2 AND (metadata->>'deleted_at') IS NULL
               RETURNING next_sequence - 1 AS seq, COALESCE(taxpayer_segment, '000') AS seg"#,
        )
        .bind(company_id).bind(period)
        .fetch_one(conn).await?;
        Ok(AllocatedSequence {
            seq: row.get("seq"),
            seg: row.get("seg"),
        })
    }
}

backbone_core::impl_crud_repository!(TaxFilingPeriodRepository, TaxFilingPeriod, soft_delete);
