//! Repository for TaxRepartitionLine entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the repartition SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxRepartitionLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use backbone_orm::company_scope;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::TaxRepartitionLine;

/// Table name for TaxRepartitionLine entities
pub const TABLE_NAME: &str = "tax.tax_repartition_lines";

/// The exact row a validated repartition-line insert writes.
pub struct NewTaxRepartitionLineRecord<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub document_type: &'a str,
    pub repartition_type: &'a str,
    pub factor_percent: Decimal,
    pub account_id: Option<Uuid>,
    pub tag_ids: &'a [Uuid],
    pub sort_order: i32,
    pub description: Option<&'a str>,
}

/// One live repartition line, as the family pre-check sees it.
#[derive(Debug, Clone)]
pub struct RepartitionLineRecord {
    pub id: Uuid,
    pub document_type: String,
    pub repartition_type: String,
    pub factor_percent: Decimal,
    pub account_id: Option<Uuid>,
    pub sort_order: i32,
}

/// Repository for TaxRepartitionLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxRepartitionLineRepository(
    backbone_orm::GenericCrudRepository<TaxRepartitionLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxRepartitionLineRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxRepartitionLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl TaxRepartitionLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Repartition SQL. Lives here (not in the service) per the module's 4-layer rule.
impl TaxRepartitionLineRepository {
    fn insert_sql() -> &'static str {
        r#"INSERT INTO tax.tax_repartition_lines
               (id, company_id, template_id, document_type, repartition_type,
                factor_percent, account_id, tag_ids, sort_order, description)
           VALUES ($1, $2, $3, $4::repartition_document_type, $5::repartition_type,
                   $6, $7, $8, $9, $10)"#
    }

    fn bind_insert<'q>(
        q: sqlx::query::Query<'q, sqlx::Postgres, sqlx::postgres::PgArguments>,
        r: &'q NewTaxRepartitionLineRecord<'_>,
    ) -> sqlx::query::Query<'q, sqlx::Postgres, sqlx::postgres::PgArguments> {
        q.bind(r.id)
            .bind(r.company_id)
            .bind(r.template_id)
            .bind(r.document_type)
            .bind(r.repartition_type)
            .bind(r.factor_percent)
            .bind(r.account_id)
            .bind(r.tag_ids)
            .bind(r.sort_order)
            .bind(r.description)
    }

    /// Insert one repartition line on an already-bound transaction connection —
    /// used by `create_template`'s auto-seed, which must land the template and
    /// both seed families atomically so the deferred family-validation trigger
    /// only ever sees a complete state.
    pub async fn insert_on(
        conn: &mut sqlx::PgConnection,
        r: &NewTaxRepartitionLineRecord<'_>,
    ) -> Result<(), sqlx::Error> {
        Self::bind_insert(sqlx::query(Self::insert_sql()), r)
            .execute(&mut *conn)
            .await?;
        Ok(())
    }

    /// Insert one repartition line as a single company-scoped statement
    /// (RLS fence): for the standalone `add_repartition_line` verb.
    pub async fn insert_scoped(
        &self,
        pool: &PgPool,
        r: &NewTaxRepartitionLineRecord<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(pool, Self::bind_insert(sqlx::query(Self::insert_sql()), r))
            .await
            .map(|_| ())
    }

    /// Soft-delete every live line of one (template, document_type) family on
    /// an already-bound transaction connection — the retire half of a family
    /// replacement. Must share a transaction with the replacement inserts: the
    /// deferred family-validation trigger would reject the intermediate
    /// family-less state at a per-statement commit.
    pub async fn soft_delete_family_on(
        conn: &mut sqlx::PgConnection,
        template_id: Uuid,
        document_type: &str,
    ) -> Result<u64, sqlx::Error> {
        sqlx::query(
            r#"UPDATE tax.tax_repartition_lines
                  SET metadata = jsonb_set(COALESCE(metadata, '{}'::jsonb),
                                           '{deleted_at}', to_jsonb(NOW()))
                WHERE template_id = $1
                  AND document_type::text = $2
                  AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(template_id)
        .bind(document_type)
        .execute(&mut *conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// Count live lines of one (template, document_type) family on an
    /// already-bound transaction connection — used to detect the pre-repartition
    /// legacy shape (zero live rows anywhere) before rewriting a family.
    pub async fn count_live_family_on(
        conn: &mut sqlx::PgConnection,
        template_id: Uuid,
        document_type: &str,
    ) -> Result<i64, sqlx::Error> {
        let n: i64 = sqlx::query_scalar(
            r#"SELECT COUNT(*) FROM tax.tax_repartition_lines
                WHERE template_id = $1
                  AND document_type::text = $2
                  AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(template_id)
        .bind(document_type)
        .fetch_one(&mut *conn)
        .await?;
        Ok(n)
    }

    /// All live repartition lines of a template (both families), ordered for
    /// display. Company-scoped (RLS fence).
    pub async fn find_for_template(
        &self,
        pool: &PgPool,
        template_id: Uuid,
    ) -> Result<Vec<RepartitionLineRecord>, sqlx::Error> {
        let rows: Vec<(Uuid, String, String, Decimal, Option<Uuid>, i32)> =
            company_scope::fetch_all_scoped(
                pool,
                sqlx::query_as(
                    r#"SELECT id, document_type::text, repartition_type::text, factor_percent,
                              account_id, sort_order
                       FROM tax.tax_repartition_lines
                       WHERE template_id = $1 AND (metadata->>'deleted_at') IS NULL
                       ORDER BY document_type::text, repartition_type::text, sort_order"#,
                )
                .bind(template_id),
            )
            .await?;
        Ok(rows
            .into_iter()
            .map(
                |(id, document_type, repartition_type, factor_percent, account_id, sort_order)| {
                    RepartitionLineRecord {
                        id,
                        document_type,
                        repartition_type,
                        factor_percent,
                        account_id,
                        sort_order,
                    }
                },
            )
            .collect())
    }
}

backbone_core::impl_crud_repository!(
    TaxRepartitionLineRepository,
    TaxRepartitionLine,
    soft_delete
);
