//! Repository for TaxTag entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the tax-tag SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxTag, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::TaxTag;

/// Table name for TaxTag entities
pub const TABLE_NAME: &str = "tax.tax_tags";

/// The exact row a validated tax-tag insert writes.
pub struct NewTaxTagRow<'a> {
    pub id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
}

/// Repository for TaxTag entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxTagRepository(backbone_orm::GenericCrudRepository<TaxTag, backbone_orm::SoftDelete>);

impl std::ops::Deref for TaxTagRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxTag, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl TaxTagRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Tax-tag SQL. Lives here (not in the service) per the module's 4-layer rule. Every statement
/// runs on a caller-provided executor — under a decorated host the transaction was bound to the
/// ambient request org scope, so the composing service's row-level fences govern these reads and
/// writes; the decorator's per-unit code unique is the duplicate backstop.
impl TaxTagRepository {
    /// Existence probe by code — the friendly duplicate-code pre-check (used by `create_tag`
    /// and the installer's find-or-create tag resolution).
    pub async fn find_by_code_on(
        &self,
        conn: &mut sqlx::PgConnection,
        code: &str,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let found: Option<Uuid> = sqlx::query_scalar(
            r#"SELECT id FROM tax.tax_tags
               WHERE code = $1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(code)
        .fetch_optional(conn)
        .await?;
        Ok(found)
    }

    /// Insert a tax tag on any executor.
    pub async fn insert_on<'e, E>(executor: E, r: &NewTaxTagRow<'_>) -> Result<(), sqlx::Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        sqlx::query(r#"INSERT INTO tax.tax_tags (id, code, name) VALUES ($1, $2, $3)"#)
            .bind(r.id)
            .bind(r.code)
            .bind(r.name)
            .execute(executor)
            .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(TaxTagRepository, TaxTag, soft_delete);
