//! Repository for TaxTemplateRow entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated-write path's template-row SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxTemplateRow, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::TaxTemplateRow;

/// Table name for TaxTemplateRow entities
pub const TABLE_NAME: &str = "tax.tax_template_rows";

/// Repository for TaxTemplateRow entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxTemplateRowRepository(
    backbone_orm::GenericCrudRepository<TaxTemplateRow, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxTemplateRowRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxTemplateRow, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl TaxTemplateRowRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated template-row insert writes.
pub struct NewTaxTemplateRowRecord<'a> {
    pub id: Uuid,
    pub template_id: Uuid,
    pub charge_type: &'a str,
    pub rate: Decimal,
    pub account_id: Option<Uuid>,
    pub is_withholding: bool,
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    pub sort_order: i32,
    pub description: Option<&'a str>,
}

/// Tax-template-row SQL. Lives here (not in the service) per the module's 4-layer rule. Every
/// statement runs on a caller-provided executor — under a decorated host the transaction was
/// bound to the ambient request org scope, so the composing service's row-level fences govern
/// these reads and writes; unfenced deployments see the whole table.
impl TaxTemplateRowRepository {
    /// Probe for an overlapping sibling at the same `sort_order` whose effective window intersects
    /// `[effective_from, effective_to]`. Two rows effective on the same date would double-charge
    /// (council 2026-07-03). Scoped to this template, so the check is per unit once the composing
    /// service's fence is installed. The `daterange && daterange` predicate and the
    /// `'infinity'::date` COALESCE are preserved verbatim from the hand-written original.
    pub async fn find_overlap(
        &self,
        conn: &mut sqlx::PgConnection,
        template_id: Uuid,
        sort_order: i32,
        effective_from: NaiveDate,
        effective_to: Option<NaiveDate>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let overlap = sqlx::query_scalar(
            r#"SELECT id FROM tax.tax_template_rows
               WHERE template_id=$1 AND sort_order=$2 AND (metadata->>'deleted_at') IS NULL
                 AND daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[]')
                     && daterange($3, COALESCE($4, 'infinity'::date), '[]')
               LIMIT 1"#,
        )
        .bind(template_id)
        .bind(sort_order)
        .bind(effective_from)
        .bind(effective_to)
        .fetch_optional(conn)
        .await?;
        Ok(overlap)
    }

    /// Insert a new template row on any executor. The `$3::charge_type` cast mirrors the original
    /// hand-written SQL exactly.
    pub async fn insert_on<'e, E>(
        executor: E,
        r: &NewTaxTemplateRowRecord<'_>,
    ) -> Result<(), sqlx::Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        sqlx::query(
            r#"INSERT INTO tax.tax_template_rows
                (id, template_id, charge_type, rate, account_id, is_withholding, effective_from,
                 effective_to, sort_order, description)
               VALUES ($1,$2,$3::charge_type,$4,$5,$6,$7,$8,$9,$10)"#,
        )
        .bind(r.id)
        .bind(r.template_id)
        .bind(r.charge_type)
        .bind(r.rate)
        .bind(r.account_id)
        .bind(r.is_withholding)
        .bind(r.effective_from)
        .bind(r.effective_to)
        .bind(r.sort_order)
        .bind(r.description)
        .execute(executor)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(TaxTemplateRowRepository, TaxTemplateRow, soft_delete);
