//! Repository for TaxTemplate entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated-write path's tax-template SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TaxTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::TaxTemplate;

/// Table name for TaxTemplate entities
pub const TABLE_NAME: &str = "tax.tax_templates";

/// Repository for TaxTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaxTemplateRepository(
    backbone_orm::GenericCrudRepository<TaxTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaxTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<TaxTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl TaxTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated tax-template insert writes. `tax_exigibility` and
/// `cash_basis_transition_account_id` are resolved against the owning unit's settings at create
/// time and MATERIALIZED here — a later posture change never rewrites existing templates.
pub struct NewTaxTemplateRow<'a> {
    pub id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub template_type: &'a str,
    pub tax_category_id: Option<Uuid>,
    pub is_inclusive: bool,
    pub tax_exigibility: &'a str,
    pub cash_basis_transition_account_id: Option<Uuid>,
}

/// Tax-template SQL. Lives here (not in the service) per the module's 4-layer rule. Every
/// statement runs on a caller-provided executor — under a decorated host the transaction was
/// bound to the ambient request org scope, so the composing service's row-level fences govern
/// these reads and writes; unfenced deployments see the whole table.
impl TaxTemplateRepository {
    /// Existence probe by id — confirms the parent template exists before appending a row.
    /// `None` = no live row (the service treats it as `TemplateNotFound`).
    pub async fn find_by_id_on(
        &self,
        conn: &mut sqlx::PgConnection,
        id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let found = sqlx::query_scalar(
            r#"SELECT id FROM tax.tax_templates
               WHERE id = $1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(id)
        .fetch_optional(conn)
        .await?;
        Ok(found)
    }

    /// Name-collision probe by template type — the friendly duplicate-name pre-check (under a
    /// decorated host the composing service's per-unit partial unique index is the raw-SQL
    /// backstop).
    pub async fn find_by_name_and_type_on(
        &self,
        conn: &mut sqlx::PgConnection,
        template_type: &str,
        name: &str,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let found = sqlx::query_scalar(
            r#"SELECT id FROM tax.tax_templates
               WHERE template_type::text = $1 AND name = $2
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(template_type)
        .bind(name)
        .fetch_optional(conn)
        .await?;
        Ok(found)
    }

    /// Code probe — lets idempotent template installation (chart + tax-template setup) skip
    /// templates that already exist for the unit instead of tripping the duplicate-code error.
    /// Under a decorated host the composing service's per-unit unique is the raw-SQL backstop.
    pub async fn find_by_code_on(
        &self,
        conn: &mut sqlx::PgConnection,
        code: &str,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let found = sqlx::query_scalar(
            r#"SELECT id FROM tax.tax_templates
               WHERE code = $1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(code)
        .fetch_optional(conn)
        .await?;
        Ok(found)
    }

    /// Insert a new active tax template on any executor — a bound transaction connection (so the
    /// template and its seeded repartition families land atomically) or the pool directly.
    /// The `$4::template_type` cast and `'active'::tax_status` literal mirror the original
    /// hand-written SQL exactly.
    pub async fn insert_on<'e, E>(executor: E, r: &NewTaxTemplateRow<'_>) -> Result<(), sqlx::Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        sqlx::query(
            r#"INSERT INTO tax.tax_templates
                   (id, code, name, template_type, tax_category_id, is_inclusive,
                    status, tax_exigibility, cash_basis_transition_account_id)
               VALUES ($1,$2,$3,$4::template_type,$5,$6,'active'::tax_status,
                       $7::tax_exigibility,$8)"#,
        )
        .bind(r.id)
        .bind(r.code)
        .bind(r.name)
        .bind(r.template_type)
        .bind(r.tax_category_id)
        .bind(r.is_inclusive)
        .bind(r.tax_exigibility)
        .bind(r.cash_basis_transition_account_id)
        .execute(executor)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(TaxTemplateRepository, TaxTemplate, soft_delete);
