//! Repository for WithholdingCategory entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated-write path's withholding SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WithholdingCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::WithholdingCategory;

/// Table name for WithholdingCategory entities
pub const TABLE_NAME: &str = "tax.withholding_categories";

/// Repository for WithholdingCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WithholdingCategoryRepository(
    backbone_orm::GenericCrudRepository<WithholdingCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WithholdingCategoryRepository {
    type Target =
        backbone_orm::GenericCrudRepository<WithholdingCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl WithholdingCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated withholding-category insert writes.
pub struct NewWithholdingCategoryRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub rate: Decimal,
    pub threshold_amount: Decimal,
    pub account_id: Option<Uuid>,
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
}

/// Withholding-category SQL. Lives here (not in the service) per the module's 4-layer rule.
impl WithholdingCategoryRepository {
    /// Probe for an overlapping effective window for `code` within this tenant (council 2026-07-03)
    /// — so `resolve_withholding` always has exactly one applicable rate on any date. The DB-level
    /// EXCLUDE (reshaped per-company by ADR-0010 B1) also enforces this; this probe gives the
    /// service a tidy error message before the constraint fires. The `daterange && daterange`
    /// predicate and the `'infinity'::date` COALESCE are preserved verbatim.
    pub async fn find_overlap(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        code: &str,
        effective_from: NaiveDate,
        effective_to: Option<NaiveDate>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let overlap = backbone_orm::company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT id FROM tax.withholding_categories
                   WHERE company_id=$1 AND code=$2 AND (metadata->>'deleted_at') IS NULL
                     AND daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[]')
                         && daterange($3, COALESCE($4, 'infinity'::date), '[]')
                   LIMIT 1"#,
            )
            .bind(company_id)
            .bind(code)
            .bind(effective_from)
            .bind(effective_to),
        )
        .await?;
        Ok(overlap)
    }

    /// Insert a new active withholding category, scoped so the RLS WITH CHECK sees
    /// `app.company_id`. A raw `.execute(pool)` ignores the request company task-local and the
    /// fence REJECTS the insert (surfaces as a 500 to the caller); the scoped helper binds the
    /// company for this statement.
    pub async fn insert(
        &self,
        pool: &PgPool,
        r: &NewWithholdingCategoryRow<'_>,
    ) -> Result<(), sqlx::Error> {
        backbone_orm::company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO tax.withholding_categories
                    (id, company_id, code, name, rate, threshold_amount, account_id, effective_from, effective_to, status)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'active'::tax_status)"#,
            )
            .bind(r.id).bind(r.company_id).bind(r.code).bind(r.name).bind(r.rate).bind(r.threshold_amount)
            .bind(r.account_id).bind(r.effective_from).bind(r.effective_to),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(
    WithholdingCategoryRepository,
    WithholdingCategory,
    soft_delete
);
