//! Validator for CompanyTaxSettings entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CompanyTaxSettings>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CompanyTaxSettings;

/// Validator type alias for CompanyTaxSettings entities.
pub type CompanyTaxSettingsValidator = EntityValidator<CompanyTaxSettings>;

/// Build a validator for CompanyTaxSettings with all schema-defined field rules.
pub fn company_tax_settings_validator() -> CompanyTaxSettingsValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
