//! Validator for TaxTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TaxTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::TaxTemplate;
use backbone_core::RequiredString;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for TaxTemplate entities.
pub type TaxTemplateValidator = EntityValidator<TaxTemplate>;

/// Build a validator for TaxTemplate with all schema-defined field rules.
pub fn tax_template_validator() -> TaxTemplateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &TaxTemplate| &e.code))
        .rule(RequiredString::new("name", |e: &TaxTemplate| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
