//! Validator for TaxTag entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TaxTag>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::TaxTag;

/// Validator type alias for TaxTag entities.
pub type TaxTagValidator = EntityValidator<TaxTag>;

/// Build a validator for TaxTag with all schema-defined field rules.
pub fn tax_tag_validator() -> TaxTagValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &TaxTag| &e.code))
        .rule(RequiredString::new("name", |e: &TaxTag| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
