//! Validator for TaxTemplateRow entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TaxTemplateRow>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::TaxTemplateRow;

/// Validator type alias for TaxTemplateRow entities.
pub type TaxTemplateRowValidator = EntityValidator<TaxTemplateRow>;

/// Build a validator for TaxTemplateRow with all schema-defined field rules.
pub fn tax_template_row_validator() -> TaxTemplateRowValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("description", |e: &TaxTemplateRow| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
