//! Validator for TaxFilingPeriod entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TaxFilingPeriod>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::TaxFilingPeriod;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};
use backbone_core::{NonNegative, OptionalNotBlank};

/// Validator type alias for TaxFilingPeriod entities.
pub type TaxFilingPeriodValidator = EntityValidator<TaxFilingPeriod>;

/// Build a validator for TaxFilingPeriod with all schema-defined field rules.
pub fn tax_filing_period_validator() -> TaxFilingPeriodValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("npwp", |e: &TaxFilingPeriod| {
            e.npwp.as_deref()
        }))
        .rule(OptionalNotBlank::new(
            "taxpayer_segment",
            |e: &TaxFilingPeriod| e.taxpayer_segment.as_deref(),
        ))
        .rule(NonNegative::new("next_sequence", |e: &TaxFilingPeriod| {
            e.next_sequence as i64
        }))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
