//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod tax_category_auth;
pub mod tax_template_auth;
pub mod tax_template_row_auth;
pub mod withholding_category_auth;

pub use tax_category_auth::{TaxCategoryPolicy, TaxCategoryGuard, TaxCategoryServiceGuard};
pub use tax_template_auth::{TaxTemplatePolicy, TaxTemplateGuard, TaxTemplateServiceGuard};
pub use tax_template_row_auth::{TaxTemplateRowPolicy, TaxTemplateRowGuard, TaxTemplateRowServiceGuard};
pub use withholding_category_auth::{WithholdingCategoryPolicy, WithholdingCategoryGuard, WithholdingCategoryServiceGuard};

// <<< CUSTOM
// END CUSTOM
