//! Auth configuration for TaxTemplate handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TaxTemplate>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TaxTemplateService;
use crate::domain::entity::TaxTemplate;

/// Permission string constants for TaxTemplate operations.
pub mod permissions {
    pub const LIST:        &str = "tax_template:list";
    pub const READ:        &str = "tax_template:read";
    pub const CREATE:      &str = "tax_template:create";
    pub const UPDATE:      &str = "tax_template:update";
    pub const DELETE:      &str = "tax_template:delete";
    pub const RESTORE:     &str = "tax_template:restore";
    pub const TRASH:       &str = "tax_template:trash";
    pub const EMPTY_TRASH: &str = "tax_template:empty_trash";
    pub const BULK_CREATE: &str = "tax_template:bulk_create";
    pub const UPSERT:      &str = "tax_template:upsert";
}

/// Resource policy for TaxTemplate — maps CRUD actions to permission strings.
pub struct TaxTemplatePolicy;

#[async_trait]
impl ResourcePolicy<TaxTemplate> for TaxTemplatePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TaxTemplate,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TaxTemplate handlers.
///
/// Wraps `TaxTemplateService` and checks `TaxTemplatePolicy` before delegating.
pub type TaxTemplateGuard = PermissionGuard<TaxTemplate>;

/// Service-integrated permission guard for TaxTemplate (for use in generated handlers).
pub type TaxTemplateServiceGuard = ServicePermissionGuard<TaxTemplate, TaxTemplateService, TaxTemplatePolicy>;

// <<< CUSTOM
// END CUSTOM
