//! Auth configuration for TaxTemplateRow handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TaxTemplateRow>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TaxTemplateRowService;
use crate::domain::entity::TaxTemplateRow;

/// Permission string constants for TaxTemplateRow operations.
pub mod permissions {
    pub const LIST:        &str = "tax_template_row:list";
    pub const READ:        &str = "tax_template_row:read";
    pub const CREATE:      &str = "tax_template_row:create";
    pub const UPDATE:      &str = "tax_template_row:update";
    pub const DELETE:      &str = "tax_template_row:delete";
    pub const RESTORE:     &str = "tax_template_row:restore";
    pub const TRASH:       &str = "tax_template_row:trash";
    pub const EMPTY_TRASH: &str = "tax_template_row:empty_trash";
    pub const BULK_CREATE: &str = "tax_template_row:bulk_create";
    pub const UPSERT:      &str = "tax_template_row:upsert";
}

/// Resource policy for TaxTemplateRow — maps CRUD actions to permission strings.
pub struct TaxTemplateRowPolicy;

#[async_trait]
impl ResourcePolicy<TaxTemplateRow> for TaxTemplateRowPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TaxTemplateRow,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TaxTemplateRow handlers.
///
/// Wraps `TaxTemplateRowService` and checks `TaxTemplateRowPolicy` before delegating.
pub type TaxTemplateRowGuard = PermissionGuard<TaxTemplateRow>;

/// Service-integrated permission guard for TaxTemplateRow (for use in generated handlers).
pub type TaxTemplateRowServiceGuard = ServicePermissionGuard<TaxTemplateRow, TaxTemplateRowService, TaxTemplateRowPolicy>;

// <<< CUSTOM
// END CUSTOM
