//! Auth configuration for TaxCategory handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TaxCategory>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TaxCategoryService;
use crate::domain::entity::TaxCategory;

/// Permission string constants for TaxCategory operations.
pub mod permissions {
    pub const LIST:        &str = "tax_category:list";
    pub const READ:        &str = "tax_category:read";
    pub const CREATE:      &str = "tax_category:create";
    pub const UPDATE:      &str = "tax_category:update";
    pub const DELETE:      &str = "tax_category:delete";
    pub const RESTORE:     &str = "tax_category:restore";
    pub const TRASH:       &str = "tax_category:trash";
    pub const EMPTY_TRASH: &str = "tax_category:empty_trash";
    pub const BULK_CREATE: &str = "tax_category:bulk_create";
    pub const UPSERT:      &str = "tax_category:upsert";
}

/// Resource policy for TaxCategory — maps CRUD actions to permission strings.
pub struct TaxCategoryPolicy;

#[async_trait]
impl ResourcePolicy<TaxCategory> for TaxCategoryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TaxCategory,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TaxCategory handlers.
///
/// Wraps `TaxCategoryService` and checks `TaxCategoryPolicy` before delegating.
pub type TaxCategoryGuard = PermissionGuard<TaxCategory>;

/// Service-integrated permission guard for TaxCategory (for use in generated handlers).
pub type TaxCategoryServiceGuard = ServicePermissionGuard<TaxCategory, TaxCategoryService, TaxCategoryPolicy>;

// <<< CUSTOM
// END CUSTOM
