//! CompanyTaxSettings API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CompanyTaxSettings CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// COMPANYTAXSETTINGS TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CompanyTaxSettings
pub struct CompanyTaxSettingsTestData;

impl TestDataGenerator for CompanyTaxSettingsTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "rounding_method": "round_globally",
            "default_exigibility": "on_invoice",
            "cash_basis_transition_account_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "rounding_method": "round_globally",
            "default_exigibility": "on_invoice",
            "cash_basis_transition_account_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// COMPANYTAXSETTINGS API TEST
// ============================================================================

/// CompanyTaxSettings API test suite
pub struct CompanyTaxSettingsApiTest {
    inner: GenericCrudTest<CompanyTaxSettingsTestData>,
}

impl CompanyTaxSettingsApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/company_tax_settings", "CompanyTaxSettings");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CompanyTaxSettingsTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CompanyTaxSettingsApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_company_tax_settings_crud() {
        let mut test = CompanyTaxSettingsApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CompanyTaxSettings specific tests here
// <<< CUSTOM TESTS END >>>
