//! EFakturDocument API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EFakturDocument CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EFAKTURDOCUMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EFakturDocument
pub struct EFakturDocumentTestData;

impl TestDataGenerator for EFakturDocumentTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "tax_transaction_id": Uuid::new_v4().to_string(),
            "number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "transaction_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "taxpayer_segment": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "period": Utc::now().format("%Y-%m-%d").to_string(),
            "sequence": 1,
            "assignment_date": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "assigned",
            "replaces_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "tax_transaction_id": Uuid::new_v4().to_string(),
            "number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "transaction_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "taxpayer_segment": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "period": Utc::now().format("%Y-%m-%d").to_string(),
            "sequence": 1,
            "assignment_date": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "assigned",
            "replaces_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/tax_transactions", &super::tax_transaction_api_test::TaxTransactionTestData).await {
            deps.push(("tax_transaction_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// EFAKTURDOCUMENT API TEST
// ============================================================================

/// EFakturDocument API test suite
pub struct EFakturDocumentApiTest {
    inner: GenericCrudTest<EFakturDocumentTestData>,
}

impl EFakturDocumentApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/efaktur_documents", "EFakturDocument");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EFakturDocumentTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EFakturDocumentApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_e_faktur_document_crud() {
        let mut test = EFakturDocumentApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EFakturDocument specific tests here
// <<< CUSTOM TESTS END >>>
