//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod tax_category_api_test;
pub mod tax_template_api_test;
pub mod tax_template_row_api_test;
pub mod withholding_category_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use tax_category_api_test::*;
pub use tax_template_api_test::*;
pub use tax_template_row_api_test::*;
pub use withholding_category_api_test::*;
