//! TaxTemplate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TaxTemplate CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TAXTEMPLATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TaxTemplate
pub struct TaxTemplateTestData;

impl TestDataGenerator for TaxTemplateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "template_type": "sales",
            "tax_category_id": null,
            "is_inclusive": false,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "template_type": "sales",
            "tax_category_id": null,
            "is_inclusive": false,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// TAXTEMPLATE API TEST
// ============================================================================

/// TaxTemplate API test suite
pub struct TaxTemplateApiTest {
    inner: GenericCrudTest<TaxTemplateTestData>,
}

impl TaxTemplateApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/tax_templates", "TaxTemplate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TaxTemplateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TaxTemplateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_tax_template_crud() {
        let mut test = TaxTemplateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TaxTemplate specific tests here
// <<< CUSTOM TESTS END >>>
