//! TaxFilingPeriod API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TaxFilingPeriod CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TAXFILINGPERIOD TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TaxFilingPeriod
pub struct TaxFilingPeriodTestData;

impl TestDataGenerator for TaxFilingPeriodTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "period": Utc::now().format("%Y-%m-%d").to_string(),
            "npwp": null,
            "taxpayer_segment": null,
            "next_sequence": 1,
            "output_total": 0,
            "input_total": 0,
            "withholding_total": 0,
            "status": "open",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "period": Utc::now().format("%Y-%m-%d").to_string(),
            "npwp": null,
            "taxpayer_segment": null,
            "next_sequence": 1,
            "output_total": 0,
            "input_total": 0,
            "withholding_total": 0,
            "status": "open",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// TAXFILINGPERIOD API TEST
// ============================================================================

/// TaxFilingPeriod API test suite
pub struct TaxFilingPeriodApiTest {
    inner: GenericCrudTest<TaxFilingPeriodTestData>,
}

impl TaxFilingPeriodApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/tax_filing_periods", "TaxFilingPeriod");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TaxFilingPeriodTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TaxFilingPeriodApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_tax_filing_period_crud() {
        let mut test = TaxFilingPeriodApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TaxFilingPeriod specific tests here
// <<< CUSTOM TESTS END >>>
