//! TaxRepartitionLine API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TaxRepartitionLine CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TAXREPARTITIONLINE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TaxRepartitionLine
pub struct TaxRepartitionLineTestData;

impl TestDataGenerator for TaxRepartitionLineTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "template_id": Uuid::new_v4().to_string(),
            "document_type": "invoice",
            "repartition_type": "base",
            "factor_percent": 0,
            "account_id": null,
            "tag_ids": json!([]),
            "sort_order": 1,
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "template_id": Uuid::new_v4().to_string(),
            "document_type": "invoice",
            "repartition_type": "base",
            "factor_percent": 0,
            "account_id": null,
            "tag_ids": json!([]),
            "sort_order": 1,
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(
            api,
            "/api/v1/tax_templates",
            &super::tax_template_api_test::TaxTemplateTestData,
        )
        .await
        {
            deps.push(("template_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// TAXREPARTITIONLINE API TEST
// ============================================================================

/// TaxRepartitionLine API test suite
pub struct TaxRepartitionLineApiTest {
    inner: GenericCrudTest<TaxRepartitionLineTestData>,
}

impl TaxRepartitionLineApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/tax_repartition_lines", "TaxRepartitionLine");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TaxRepartitionLineTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TaxRepartitionLineApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_tax_repartition_line_crud() {
        let mut test = TaxRepartitionLineApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TaxRepartitionLine specific tests here
// <<< CUSTOM TESTS END >>>
