//! TaxCategory API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TaxCategory CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TAXCATEGORY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TaxCategory
pub struct TaxCategoryTestData;

impl TestDataGenerator for TaxCategoryTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "tax_kind": "vat",
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "tax_kind": "vat",
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// TAXCATEGORY API TEST
// ============================================================================

/// TaxCategory API test suite
pub struct TaxCategoryApiTest {
    inner: GenericCrudTest<TaxCategoryTestData>,
}

impl TaxCategoryApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/tax_categories", "TaxCategory");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TaxCategoryTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TaxCategoryApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_tax_category_crud() {
        let mut test = TaxCategoryApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TaxCategory specific tests here
// <<< CUSTOM TESTS END >>>
