//! WithholdingCategory API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the WithholdingCategory CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// WITHHOLDINGCATEGORY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for WithholdingCategory
pub struct WithholdingCategoryTestData;

impl TestDataGenerator for WithholdingCategoryTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "rate": 0,
            "threshold_amount": 0,
            "account_id": null,
            "effective_from": Utc::now().format("%Y-%m-%d").to_string(),
            "effective_to": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "rate": 0,
            "threshold_amount": 0,
            "account_id": null,
            "effective_from": Utc::now().format("%Y-%m-%d").to_string(),
            "effective_to": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// WITHHOLDINGCATEGORY API TEST
// ============================================================================

/// WithholdingCategory API test suite
pub struct WithholdingCategoryApiTest {
    inner: GenericCrudTest<WithholdingCategoryTestData>,
}

impl WithholdingCategoryApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/withholding_categories", "WithholdingCategory");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, WithholdingCategoryTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for WithholdingCategoryApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_withholding_category_crud() {
        let mut test = WithholdingCategoryApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add WithholdingCategory specific tests here
// <<< CUSTOM TESTS END >>>
