//! Tax Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::TaxCategoryService;
use crate::application::service::TaxTemplateService;
use crate::application::service::TaxTemplateRowService;
use crate::application::service::WithholdingCategoryService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// TaxCategory service
    pub tax_category_service: Arc<TaxCategoryService>,
    /// TaxTemplate service
    pub tax_template_service: Arc<TaxTemplateService>,
    /// TaxTemplateRow service
    pub tax_template_row_service: Arc<TaxTemplateRowService>,
    /// WithholdingCategory service
    pub withholding_category_service: Arc<WithholdingCategoryService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        tax_category_service: Arc<TaxCategoryService>,
        tax_template_service: Arc<TaxTemplateService>,
        tax_template_row_service: Arc<TaxTemplateRowService>,
        withholding_category_service: Arc<WithholdingCategoryService>
    ) -> Self {
        Self {
            tax_category_service,
            tax_template_service,
            tax_template_row_service,
            withholding_category_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::TaxModule) -> Self {
        Self {
            tax_category_service: module.tax_category_service.clone(),
            tax_template_service: module.tax_template_service.clone(),
            tax_template_row_service: module.tax_template_row_service.clone(),
            withholding_category_service: module.withholding_category_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    tax_category_service: Option<Arc<TaxCategoryService>>,
    tax_template_service: Option<Arc<TaxTemplateService>>,
    tax_template_row_service: Option<Arc<TaxTemplateRowService>>,
    withholding_category_service: Option<Arc<WithholdingCategoryService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the TaxCategory service.
    pub fn with_tax_category_service(mut self, service: Arc<TaxCategoryService>) -> Self {
        self.tax_category_service = Some(service);
        self
    }

    /// Set the TaxTemplate service.
    pub fn with_tax_template_service(mut self, service: Arc<TaxTemplateService>) -> Self {
        self.tax_template_service = Some(service);
        self
    }

    /// Set the TaxTemplateRow service.
    pub fn with_tax_template_row_service(mut self, service: Arc<TaxTemplateRowService>) -> Self {
        self.tax_template_row_service = Some(service);
        self
    }

    /// Set the WithholdingCategory service.
    pub fn with_withholding_category_service(mut self, service: Arc<WithholdingCategoryService>) -> Self {
        self.withholding_category_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            tax_category_service: self.tax_category_service.expect("tax_category_service is required"),
            tax_template_service: self.tax_template_service.expect("tax_template_service is required"),
            tax_template_row_service: self.tax_template_row_service.expect("tax_template_row_service is required"),
            withholding_category_service: self.withholding_category_service.expect("withholding_category_service is required"),
        }
    }
}
