//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    company_tax_settings_handler::create_company_tax_settings_routes,
    tax_category_handler::create_tax_category_routes,
    tax_transaction_handler::create_tax_transaction_routes,
    e_faktur_document_handler::create_e_faktur_document_routes,
    tax_filing_period_handler::create_tax_filing_period_routes,
    tax_tag_handler::create_tax_tag_routes,
    tax_repartition_line_handler::create_tax_repartition_line_routes,
    tax_template_handler::create_tax_template_routes,
    tax_template_row_handler::create_tax_template_row_routes,
    withholding_category_handler::create_withholding_category_routes,
};

use crate::application::service::{
    CompanyTaxSettingsService,
    TaxCategoryService,
    TaxTransactionService,
    EFakturDocumentService,
    TaxFilingPeriodService,
    TaxTagService,
    TaxRepartitionLineService,
    TaxTemplateService,
    TaxTemplateRowService,
    WithholdingCategoryService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub company_tax_settings: Arc<CompanyTaxSettingsService>,
    pub tax_category: Arc<TaxCategoryService>,
    pub tax_transaction: Arc<TaxTransactionService>,
    pub e_faktur_document: Arc<EFakturDocumentService>,
    pub tax_filing_period: Arc<TaxFilingPeriodService>,
    pub tax_tag: Arc<TaxTagService>,
    pub tax_repartition_line: Arc<TaxRepartitionLineService>,
    pub tax_template: Arc<TaxTemplateService>,
    pub tax_template_row: Arc<TaxTemplateRowService>,
    pub withholding_category: Arc<WithholdingCategoryService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // CompanyTaxSettings routes (12 Backbone endpoints)
        .merge(create_company_tax_settings_routes(services.company_tax_settings))
        // TaxCategory routes (12 Backbone endpoints)
        .merge(create_tax_category_routes(services.tax_category))
        // TaxTransaction routes (12 Backbone endpoints)
        .merge(create_tax_transaction_routes(services.tax_transaction))
        // EFakturDocument routes (12 Backbone endpoints)
        .merge(create_e_faktur_document_routes(services.e_faktur_document))
        // TaxFilingPeriod routes (12 Backbone endpoints)
        .merge(create_tax_filing_period_routes(services.tax_filing_period))
        // TaxTag routes (12 Backbone endpoints)
        .merge(create_tax_tag_routes(services.tax_tag))
        // TaxRepartitionLine routes (12 Backbone endpoints)
        .merge(create_tax_repartition_line_routes(services.tax_repartition_line))
        // TaxTemplate routes (12 Backbone endpoints)
        .merge(create_tax_template_routes(services.tax_template))
        // TaxTemplateRow routes (12 Backbone endpoints)
        .merge(create_tax_template_row_routes(services.tax_template_row))
        // WithholdingCategory routes (12 Backbone endpoints)
        .merge(create_withholding_category_routes(services.withholding_category))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn company_tax_settings_routes(service: Arc<CompanyTaxSettingsService>) -> Router {
        create_company_tax_settings_routes(service)
    }

    pub fn tax_category_routes(service: Arc<TaxCategoryService>) -> Router {
        create_tax_category_routes(service)
    }

    pub fn tax_transaction_routes(service: Arc<TaxTransactionService>) -> Router {
        create_tax_transaction_routes(service)
    }

    pub fn e_faktur_document_routes(service: Arc<EFakturDocumentService>) -> Router {
        create_e_faktur_document_routes(service)
    }

    pub fn tax_filing_period_routes(service: Arc<TaxFilingPeriodService>) -> Router {
        create_tax_filing_period_routes(service)
    }

    pub fn tax_tag_routes(service: Arc<TaxTagService>) -> Router {
        create_tax_tag_routes(service)
    }

    pub fn tax_repartition_line_routes(service: Arc<TaxRepartitionLineService>) -> Router {
        create_tax_repartition_line_routes(service)
    }

    pub fn tax_template_routes(service: Arc<TaxTemplateService>) -> Router {
        create_tax_template_routes(service)
    }

    pub fn tax_template_row_routes(service: Arc<TaxTemplateRowService>) -> Router {
        create_tax_template_row_routes(service)
    }

    pub fn withholding_category_routes(service: Arc<WithholdingCategoryService>) -> Router {
        create_withholding_category_routes(service)
    }

}
