//! Public services for Tax module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Tax module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait TaxQueryService: Send + Sync {
    /// Get TaxCategory by ID
    async fn get_tax_category(&self, id: TaxCategoryId) -> Result<Option<TaxCategoryDto>>;

    /// Get TaxCategory summary by ID
    async fn get_tax_category_summary(&self, id: TaxCategoryId) -> Result<Option<TaxCategorySummary>>;

    /// Check if TaxCategory exists
    async fn tax_category_exists(&self, id: TaxCategoryId) -> Result<bool>;

    /// Get TaxTemplate by ID
    async fn get_tax_template(&self, id: TaxTemplateId) -> Result<Option<TaxTemplateDto>>;

    /// Get TaxTemplate summary by ID
    async fn get_tax_template_summary(&self, id: TaxTemplateId) -> Result<Option<TaxTemplateSummary>>;

    /// Check if TaxTemplate exists
    async fn tax_template_exists(&self, id: TaxTemplateId) -> Result<bool>;

    /// Get TaxTemplateRow by ID
    async fn get_tax_template_row(&self, id: TaxTemplateRowId) -> Result<Option<TaxTemplateRowDto>>;

    /// Get TaxTemplateRow summary by ID
    async fn get_tax_template_row_summary(&self, id: TaxTemplateRowId) -> Result<Option<TaxTemplateRowSummary>>;

    /// Check if TaxTemplateRow exists
    async fn tax_template_row_exists(&self, id: TaxTemplateRowId) -> Result<bool>;

    /// Get WithholdingCategory by ID
    async fn get_withholding_category(&self, id: WithholdingCategoryId) -> Result<Option<WithholdingCategoryDto>>;

    /// Get WithholdingCategory summary by ID
    async fn get_withholding_category_summary(&self, id: WithholdingCategoryId) -> Result<Option<WithholdingCategorySummary>>;

    /// Check if WithholdingCategory exists
    async fn withholding_category_exists(&self, id: WithholdingCategoryId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of TaxQueryService
pub struct TaxQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> TaxQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
