//! Public types for Tax module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// TAXCATEGORY TYPES
// ============================================================================

/// Type-safe ID for TaxCategory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxCategoryId(pub Uuid);

impl TaxCategoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxCategoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxCategoryId> for Uuid {
    fn from(id: TaxCategoryId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxCategory
///
/// This is the public representation of TaxCategory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxCategoryDto {
    pub id: TaxCategoryId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub tax_kind: TaxKind,
    pub status: TaxStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxCategory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxCategorySummary {
    pub id: TaxCategoryId,
    pub name: String,
    pub status: TaxStatus,
}

/// Reference to TaxCategory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxCategoryRef {
    pub id: TaxCategoryId,
}

// ============================================================================
// TAXTRANSACTION TYPES
// ============================================================================

/// Type-safe ID for TaxTransaction
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxTransactionId(pub Uuid);

impl TaxTransactionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxTransactionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxTransactionId> for Uuid {
    fn from(id: TaxTransactionId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxTransaction
///
/// This is the public representation of TaxTransaction for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTransactionDto {
    pub id: TaxTransactionId,
    pub company_id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: InvoiceKind,
    pub posting_date: NaiveDate,
    pub taxable_base: Decimal,
    pub output_total: Decimal,
    pub input_total: Decimal,
    pub withholding_total: Decimal,
    pub currency: String,
    pub source: TaxTransactionSource,
    pub efaktur_document_id: Option<Uuid>,
    pub status: TaxTransactionStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxTransaction for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTransactionSummary {
    pub id: TaxTransactionId,
    pub status: TaxTransactionStatus,
}

/// Reference to TaxTransaction for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTransactionRef {
    pub id: TaxTransactionId,
}

// ============================================================================
// EFAKTURDOCUMENT TYPES
// ============================================================================

/// Type-safe ID for EFakturDocument
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EFakturDocumentId(pub Uuid);

impl EFakturDocumentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EFakturDocumentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EFakturDocumentId> for Uuid {
    fn from(id: EFakturDocumentId) -> Self {
        id.0
    }
}

/// Data transfer object for EFakturDocument
///
/// This is the public representation of EFakturDocument for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EFakturDocumentDto {
    pub id: EFakturDocumentId,
    pub company_id: Uuid,
    pub tax_transaction_id: Uuid,
    pub number: String,
    pub transaction_code: String,
    pub taxpayer_segment: String,
    pub period: NaiveDate,
    pub sequence: i32,
    pub assignment_date: NaiveDate,
    pub status: EFakturStatus,
    pub replaces_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of EFakturDocument for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EFakturDocumentSummary {
    pub id: EFakturDocumentId,
    pub status: EFakturStatus,
}

/// Reference to EFakturDocument for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EFakturDocumentRef {
    pub id: EFakturDocumentId,
}

// ============================================================================
// TAXFILINGPERIOD TYPES
// ============================================================================

/// Type-safe ID for TaxFilingPeriod
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxFilingPeriodId(pub Uuid);

impl TaxFilingPeriodId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxFilingPeriodId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxFilingPeriodId> for Uuid {
    fn from(id: TaxFilingPeriodId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxFilingPeriod
///
/// This is the public representation of TaxFilingPeriod for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxFilingPeriodDto {
    pub id: TaxFilingPeriodId,
    pub company_id: Uuid,
    pub period: NaiveDate,
    pub npwp: Option<String>,
    pub taxpayer_segment: Option<String>,
    pub next_sequence: i32,
    pub output_total: Decimal,
    pub input_total: Decimal,
    pub withholding_total: Decimal,
    pub status: TaxFilingStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxFilingPeriod for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxFilingPeriodSummary {
    pub id: TaxFilingPeriodId,
    pub status: TaxFilingStatus,
}

/// Reference to TaxFilingPeriod for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxFilingPeriodRef {
    pub id: TaxFilingPeriodId,
}

// ============================================================================
// TAXTEMPLATE TYPES
// ============================================================================

/// Type-safe ID for TaxTemplate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxTemplateId(pub Uuid);

impl TaxTemplateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxTemplateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxTemplateId> for Uuid {
    fn from(id: TaxTemplateId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxTemplate
///
/// This is the public representation of TaxTemplate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateDto {
    pub id: TaxTemplateId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub template_type: TemplateType,
    pub tax_category_id: Option<Uuid>,
    pub is_inclusive: bool,
    pub status: TaxStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxTemplate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateSummary {
    pub id: TaxTemplateId,
    pub name: String,
    pub status: TaxStatus,
}

/// Reference to TaxTemplate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRef {
    pub id: TaxTemplateId,
}

// ============================================================================
// TAXTEMPLATEROW TYPES
// ============================================================================

/// Type-safe ID for TaxTemplateRow
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxTemplateRowId(pub Uuid);

impl TaxTemplateRowId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxTemplateRowId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxTemplateRowId> for Uuid {
    fn from(id: TaxTemplateRowId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxTemplateRow
///
/// This is the public representation of TaxTemplateRow for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRowDto {
    pub id: TaxTemplateRowId,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub charge_type: ChargeType,
    pub rate: Decimal,
    pub account_id: Option<Uuid>,
    pub is_withholding: bool,
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    pub sort_order: i32,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxTemplateRow for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRowSummary {
    pub id: TaxTemplateRowId,
}

/// Reference to TaxTemplateRow for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRowRef {
    pub id: TaxTemplateRowId,
}

// ============================================================================
// WITHHOLDINGCATEGORY TYPES
// ============================================================================

/// Type-safe ID for WithholdingCategory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WithholdingCategoryId(pub Uuid);

impl WithholdingCategoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for WithholdingCategoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<WithholdingCategoryId> for Uuid {
    fn from(id: WithholdingCategoryId) -> Self {
        id.0
    }
}

/// Data transfer object for WithholdingCategory
///
/// This is the public representation of WithholdingCategory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WithholdingCategoryDto {
    pub id: WithholdingCategoryId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub rate: Decimal,
    pub threshold_amount: Decimal,
    pub account_id: Option<Uuid>,
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    pub status: TaxStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of WithholdingCategory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WithholdingCategorySummary {
    pub id: WithholdingCategoryId,
    pub name: String,
    pub status: TaxStatus,
}

/// Reference to WithholdingCategory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WithholdingCategoryRef {
    pub id: WithholdingCategoryId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
