//! Public types for Tax module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// TAXCATEGORY TYPES
// ============================================================================

/// Type-safe ID for TaxCategory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxCategoryId(pub Uuid);

impl TaxCategoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxCategoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxCategoryId> for Uuid {
    fn from(id: TaxCategoryId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxCategory
///
/// This is the public representation of TaxCategory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxCategoryDto {
    pub id: TaxCategoryId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub tax_kind: TaxKind,
    pub status: TaxStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxCategory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxCategorySummary {
    pub id: TaxCategoryId,
    pub name: String,
    pub status: TaxStatus,
}

/// Reference to TaxCategory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxCategoryRef {
    pub id: TaxCategoryId,
}

// ============================================================================
// TAXTEMPLATE TYPES
// ============================================================================

/// Type-safe ID for TaxTemplate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxTemplateId(pub Uuid);

impl TaxTemplateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxTemplateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxTemplateId> for Uuid {
    fn from(id: TaxTemplateId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxTemplate
///
/// This is the public representation of TaxTemplate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateDto {
    pub id: TaxTemplateId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub template_type: TemplateType,
    pub tax_category_id: Option<Uuid>,
    pub is_inclusive: bool,
    pub status: TaxStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxTemplate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateSummary {
    pub id: TaxTemplateId,
    pub name: String,
    pub status: TaxStatus,
}

/// Reference to TaxTemplate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRef {
    pub id: TaxTemplateId,
}

// ============================================================================
// TAXTEMPLATEROW TYPES
// ============================================================================

/// Type-safe ID for TaxTemplateRow
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaxTemplateRowId(pub Uuid);

impl TaxTemplateRowId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaxTemplateRowId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaxTemplateRowId> for Uuid {
    fn from(id: TaxTemplateRowId) -> Self {
        id.0
    }
}

/// Data transfer object for TaxTemplateRow
///
/// This is the public representation of TaxTemplateRow for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRowDto {
    pub id: TaxTemplateRowId,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub charge_type: ChargeType,
    pub rate: Decimal,
    pub account_id: Option<Uuid>,
    pub is_withholding: bool,
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    pub sort_order: i32,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of TaxTemplateRow for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRowSummary {
    pub id: TaxTemplateRowId,
}

/// Reference to TaxTemplateRow for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaxTemplateRowRef {
    pub id: TaxTemplateRowId,
}

// ============================================================================
// WITHHOLDINGCATEGORY TYPES
// ============================================================================

/// Type-safe ID for WithholdingCategory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WithholdingCategoryId(pub Uuid);

impl WithholdingCategoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for WithholdingCategoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<WithholdingCategoryId> for Uuid {
    fn from(id: WithholdingCategoryId) -> Self {
        id.0
    }
}

/// Data transfer object for WithholdingCategory
///
/// This is the public representation of WithholdingCategory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WithholdingCategoryDto {
    pub id: WithholdingCategoryId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub rate: Decimal,
    pub threshold_amount: Decimal,
    pub account_id: Option<Uuid>,
    pub effective_from: NaiveDate,
    pub effective_to: Option<NaiveDate>,
    pub status: TaxStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of WithholdingCategory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WithholdingCategorySummary {
    pub id: WithholdingCategoryId,
    pub name: String,
    pub status: TaxStatus,
}

/// Reference to WithholdingCategory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WithholdingCategoryRef {
    pub id: WithholdingCategoryId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
