//! Tax Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod application;
pub mod domain;
pub mod exports;
pub mod infrastructure;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CompanyTaxSettingsService;
pub use application::service::EFakturDocumentService;
pub use application::service::TaxCategoryService;
pub use application::service::TaxFilingPeriodService;
pub use application::service::TaxRepartitionLineService;
pub use application::service::TaxTagService;
pub use application::service::TaxTemplateRowService;
pub use application::service::TaxTemplateService;
pub use application::service::TaxTransactionService;
pub use application::service::WithholdingCategoryService;

// <<< CUSTOM
pub use application::service::{
    DocumentTaxLine, DocumentTaxRequest, DocumentTaxRequestLine, DocumentTaxResult, DocumentType,
    NewCategory, NewCompanySettings, NewRepartitionLine, NewRepartitionSplit, NewTag, NewTemplate,
    NewTemplateRow, NewWithholding, ReplaceRepartitionFamily, TaxEngine, TaxError, TaxLine,
    TaxWriteService,
};
// Document-grade rounding primitives (round_globally redistribution math) —
// public so the rounding unit oracle can pin them from integration tests.
pub use application::service::{distribute_delta_smoothly, round2, RoundingMethod};
// The e-Faktur + tax-recording seam. The composition ACL calls
// `EFakturService::record_tax_transaction` when billing emits a posted event —
// this is the inbound audit-mirror write path (see docs/fsd.md).
pub use application::service::{EFakturService, PostedForTax, TaxComplianceError};
pub use presentation::http::create_guarded_tax_routes;
// END CUSTOM
use axum::Router;
use sqlx::PgPool;
use std::sync::Arc;

/// Tax module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let tax = TaxModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = tax.all_crud_routes();
/// ```
pub struct TaxModule {
    pub(crate) company_tax_settings_service: Arc<CompanyTaxSettingsService>,
    pub(crate) tax_category_service: Arc<TaxCategoryService>,
    pub(crate) tax_transaction_service: Arc<TaxTransactionService>,
    pub(crate) e_faktur_document_service: Arc<EFakturDocumentService>,
    pub(crate) tax_filing_period_service: Arc<TaxFilingPeriodService>,
    pub(crate) tax_tag_service: Arc<TaxTagService>,
    pub(crate) tax_repartition_line_service: Arc<TaxRepartitionLineService>,
    pub(crate) tax_template_service: Arc<TaxTemplateService>,
    pub(crate) tax_template_row_service: Arc<TaxTemplateRowService>,
    pub(crate) withholding_category_service: Arc<WithholdingCategoryService>,
    // <<< CUSTOM
    /// The region-neutral tax engine (compute tax lines). Public so producing
    /// modules (billing/selling/buying) can call it in-process and attach the
    /// returned lines to their own AccountingPost (FSD: "tax contributes lines,
    /// not a posting").
    pub tax_engine: Arc<TaxEngine>,
    /// Validated tax-config writes (mounted as guarded HTTP routes).
    pub tax_write_service: Arc<TaxWriteService>,
    /// The e-Faktur + tax-recording seam. Public so the composition ACL can call
    /// `record_tax_transaction` when billing emits SalesInvoicePosted /
    /// PurchaseInvoicePosted — the inbound audit-mirror write path.
    pub efaktur_service: Arc<EFakturService>,
    // END CUSTOM
}

impl TaxModule {
    /// Create a new module builder
    pub fn builder() -> TaxModuleBuilder {
        TaxModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_company_tax_settings_routes, create_e_faktur_document_routes,
            create_tax_category_routes, create_tax_filing_period_routes,
            create_tax_repartition_line_routes, create_tax_tag_routes, create_tax_template_routes,
            create_tax_template_row_routes, create_tax_transaction_routes,
            create_withholding_category_routes,
        };

        Router::new()
            .merge(create_company_tax_settings_routes(
                self.company_tax_settings_service.clone(),
            ))
            .merge(create_tax_category_routes(
                self.tax_category_service.clone(),
            ))
            .merge(create_tax_transaction_routes(
                self.tax_transaction_service.clone(),
            ))
            .merge(create_e_faktur_document_routes(
                self.e_faktur_document_service.clone(),
            ))
            .merge(create_tax_filing_period_routes(
                self.tax_filing_period_service.clone(),
            ))
            .merge(create_tax_tag_routes(self.tax_tag_service.clone()))
            .merge(create_tax_repartition_line_routes(
                self.tax_repartition_line_service.clone(),
            ))
            .merge(create_tax_template_routes(
                self.tax_template_service.clone(),
            ))
            .merge(create_tax_template_row_routes(
                self.tax_template_row_service.clone(),
            ))
            .merge(create_withholding_category_routes(
                self.withholding_category_service.clone(),
            ))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(
        note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface"
    )]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_company_tax_settings_read_routes, create_e_faktur_document_read_routes,
            create_tax_category_read_routes, create_tax_filing_period_read_routes,
            create_tax_repartition_line_read_routes, create_tax_tag_read_routes,
            create_tax_template_read_routes, create_tax_template_row_read_routes,
            create_tax_transaction_read_routes, create_withholding_category_read_routes,
        };

        Router::new()
            .merge(create_company_tax_settings_read_routes(
                self.company_tax_settings_service.clone(),
            ))
            .merge(create_tax_category_read_routes(
                self.tax_category_service.clone(),
            ))
            .merge(create_tax_transaction_read_routes(
                self.tax_transaction_service.clone(),
            ))
            .merge(create_e_faktur_document_read_routes(
                self.e_faktur_document_service.clone(),
            ))
            .merge(create_tax_filing_period_read_routes(
                self.tax_filing_period_service.clone(),
            ))
            .merge(create_tax_tag_read_routes(self.tax_tag_service.clone()))
            .merge(create_tax_repartition_line_read_routes(
                self.tax_repartition_line_service.clone(),
            ))
            .merge(create_tax_template_read_routes(
                self.tax_template_service.clone(),
            ))
            .merge(create_tax_template_row_read_routes(
                self.tax_template_row_service.clone(),
            ))
            .merge(create_withholding_category_read_routes(
                self.withholding_category_service.clone(),
            ))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for TaxModule
pub struct TaxModuleBuilder {
    db_pool: Option<PgPool>,
}

impl TaxModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self { db_pool: None }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<TaxModule> {
        let db_pool = self
            .db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // CompanyTaxSettings service
        let company_tax_settings_repository =
            Arc::new(CompanyTaxSettingsRepository::new(db_pool.clone()));
        let company_tax_settings_service = Arc::new(CompanyTaxSettingsService::with_repository(
            company_tax_settings_repository.clone(),
        ));

        // TaxCategory service
        let tax_category_repository = Arc::new(TaxCategoryRepository::new(db_pool.clone()));
        let tax_category_service = Arc::new(TaxCategoryService::with_repository(
            tax_category_repository.clone(),
        ));

        // TaxTransaction service
        let tax_transaction_repository = Arc::new(TaxTransactionRepository::new(db_pool.clone()));
        let tax_transaction_service = Arc::new(TaxTransactionService::with_repository(
            tax_transaction_repository.clone(),
        ));

        // EFakturDocument service
        let e_faktur_document_repository =
            Arc::new(EFakturDocumentRepository::new(db_pool.clone()));
        let e_faktur_document_service = Arc::new(EFakturDocumentService::with_repository(
            e_faktur_document_repository.clone(),
        ));

        // TaxFilingPeriod service
        let tax_filing_period_repository =
            Arc::new(TaxFilingPeriodRepository::new(db_pool.clone()));
        let tax_filing_period_service = Arc::new(TaxFilingPeriodService::with_repository(
            tax_filing_period_repository.clone(),
        ));

        // TaxTag service
        let tax_tag_repository = Arc::new(TaxTagRepository::new(db_pool.clone()));
        let tax_tag_service = Arc::new(TaxTagService::with_repository(tax_tag_repository.clone()));

        // TaxRepartitionLine service
        let tax_repartition_line_repository =
            Arc::new(TaxRepartitionLineRepository::new(db_pool.clone()));
        let tax_repartition_line_service = Arc::new(TaxRepartitionLineService::with_repository(
            tax_repartition_line_repository.clone(),
        ));

        // TaxTemplate service
        let tax_template_repository = Arc::new(TaxTemplateRepository::new(db_pool.clone()));
        let tax_template_service = Arc::new(TaxTemplateService::with_repository(
            tax_template_repository.clone(),
        ));

        // TaxTemplateRow service
        let tax_template_row_repository = Arc::new(TaxTemplateRowRepository::new(db_pool.clone()));
        let tax_template_row_service = Arc::new(TaxTemplateRowService::with_repository(
            tax_template_row_repository.clone(),
        ));

        // WithholdingCategory service
        let withholding_category_repository =
            Arc::new(WithholdingCategoryRepository::new(db_pool.clone()));
        let withholding_category_service = Arc::new(WithholdingCategoryService::with_repository(
            withholding_category_repository.clone(),
        ));

        // <<< CUSTOM
        let tax_engine = Arc::new(TaxEngine::new(db_pool.clone()));
        let tax_write_service = Arc::new(TaxWriteService::new(db_pool.clone()));
        let efaktur_service = Arc::new(EFakturService::new(db_pool.clone()));
        // END CUSTOM

        Ok(TaxModule {
            company_tax_settings_service,
            tax_category_service,
            tax_transaction_service,
            e_faktur_document_service,
            tax_filing_period_service,
            tax_tag_service,
            tax_repartition_line_service,
            tax_template_service,
            tax_template_row_service,
            withholding_category_service,
            // <<< CUSTOM
            tax_engine,
            tax_write_service,
            efaktur_service,
            // END CUSTOM
        })
    }
}

impl Default for TaxModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
