//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod tax_category_usecases;
pub mod tax_template_usecases;
pub mod tax_template_row_usecases;
pub mod withholding_category_usecases;

pub use tax_category_usecases::{
    CreateTaxCategoryUseCase, UpdateTaxCategoryUseCase, GetTaxCategoryUseCase,
    DeleteTaxCategoryUseCase, ListTaxCategoryUseCase,
};
pub use tax_template_usecases::{
    CreateTaxTemplateUseCase, UpdateTaxTemplateUseCase, GetTaxTemplateUseCase,
    DeleteTaxTemplateUseCase, ListTaxTemplateUseCase,
};
pub use tax_template_row_usecases::{
    CreateTaxTemplateRowUseCase, UpdateTaxTemplateRowUseCase, GetTaxTemplateRowUseCase,
    DeleteTaxTemplateRowUseCase, ListTaxTemplateRowUseCase,
};
pub use withholding_category_usecases::{
    CreateWithholdingCategoryUseCase, UpdateWithholdingCategoryUseCase, GetWithholdingCategoryUseCase,
    DeleteWithholdingCategoryUseCase, ListWithholdingCategoryUseCase,
};

// <<< CUSTOM
// END CUSTOM
