//! Use case type aliases for TaxTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTaxTransactionDto, UpdateTaxTransactionDto};
use crate::application::service::TaxTransactionService;
use crate::domain::entity::TaxTransaction;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTaxTransactionUseCase = CreateUseCase<TaxTransaction, CreateTaxTransactionDto, TaxTransactionService>;
pub type UpdateTaxTransactionUseCase = UpdateUseCase<TaxTransaction, UpdateTaxTransactionDto, TaxTransactionService>;
pub type GetTaxTransactionUseCase    = GetUseCase<TaxTransaction, TaxTransactionService>;
pub type DeleteTaxTransactionUseCase = DeleteUseCase<TaxTransaction, TaxTransactionService>;
pub type ListTaxTransactionUseCase   = ListUseCase<TaxTransaction, TaxTransactionService>;

// <<< CUSTOM
// END CUSTOM
