//! Use case type aliases for TaxFilingPeriod aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTaxFilingPeriodDto, UpdateTaxFilingPeriodDto};
use crate::application::service::TaxFilingPeriodService;
use crate::domain::entity::TaxFilingPeriod;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTaxFilingPeriodUseCase = CreateUseCase<TaxFilingPeriod, CreateTaxFilingPeriodDto, TaxFilingPeriodService>;
pub type UpdateTaxFilingPeriodUseCase = UpdateUseCase<TaxFilingPeriod, UpdateTaxFilingPeriodDto, TaxFilingPeriodService>;
pub type GetTaxFilingPeriodUseCase    = GetUseCase<TaxFilingPeriod, TaxFilingPeriodService>;
pub type DeleteTaxFilingPeriodUseCase = DeleteUseCase<TaxFilingPeriod, TaxFilingPeriodService>;
pub type ListTaxFilingPeriodUseCase   = ListUseCase<TaxFilingPeriod, TaxFilingPeriodService>;

// <<< CUSTOM
// END CUSTOM
