//! Use case type aliases for TaxTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTaxTemplateDto, UpdateTaxTemplateDto};
use crate::application::service::TaxTemplateService;
use crate::domain::entity::TaxTemplate;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTaxTemplateUseCase = CreateUseCase<TaxTemplate, CreateTaxTemplateDto, TaxTemplateService>;
pub type UpdateTaxTemplateUseCase = UpdateUseCase<TaxTemplate, UpdateTaxTemplateDto, TaxTemplateService>;
pub type GetTaxTemplateUseCase    = GetUseCase<TaxTemplate, TaxTemplateService>;
pub type DeleteTaxTemplateUseCase = DeleteUseCase<TaxTemplate, TaxTemplateService>;
pub type ListTaxTemplateUseCase   = ListUseCase<TaxTemplate, TaxTemplateService>;

// <<< CUSTOM
// END CUSTOM
