//! Use case type aliases for WithholdingCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateWithholdingCategoryDto, UpdateWithholdingCategoryDto};
use crate::application::service::WithholdingCategoryService;
use crate::domain::entity::WithholdingCategory;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateWithholdingCategoryUseCase = CreateUseCase<WithholdingCategory, CreateWithholdingCategoryDto, WithholdingCategoryService>;
pub type UpdateWithholdingCategoryUseCase = UpdateUseCase<WithholdingCategory, UpdateWithholdingCategoryDto, WithholdingCategoryService>;
pub type GetWithholdingCategoryUseCase    = GetUseCase<WithholdingCategory, WithholdingCategoryService>;
pub type DeleteWithholdingCategoryUseCase = DeleteUseCase<WithholdingCategory, WithholdingCategoryService>;
pub type ListWithholdingCategoryUseCase   = ListUseCase<WithholdingCategory, WithholdingCategoryService>;

// <<< CUSTOM
// END CUSTOM
