//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod tax_category_handler;
pub mod tax_template_handler;
pub mod tax_template_row_handler;
pub mod withholding_category_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use tax_category_handler::{create_tax_category_routes, create_tax_category_read_routes, create_tax_category_write_routes};
pub use tax_template_handler::{create_tax_template_routes, create_tax_template_read_routes, create_tax_template_write_routes};
pub use tax_template_row_handler::{create_tax_template_row_routes, create_tax_template_row_read_routes, create_tax_template_row_write_routes};
pub use withholding_category_handler::{create_withholding_category_routes, create_withholding_category_read_routes, create_withholding_category_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_tax_routes;
// END CUSTOM